# #####################################################################################
#
# SYSTEM - Snapshot
#
# #####################################################################################
# System - Window Cam Snapshot on Motion
# ##################################
- alias: system_snapshot_window
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_g3_flex_window
      from: 'off'
      to: 'on'
  condition:
    - condition: template
      value_template: "{{(as_timestamp(now())-as_timestamp(state_attr('automation.system_snapshot_window','last_triggered'))|int) > 10 }}"
  action:
    - service: notify.telegram_cam
      data:
        title: "{{states('sensor.time')}} {{states('sensor.date')}}"
        message: "{{states('sensor.time')}} {{states('sensor.date')}}"
        data:
          photo:
          - url: !secret window_snap
            caption: "Window {{states('sensor.time')}} {{states('sensor.date')}}"

# ##################################
# System - Yard Cam Snapshot on Motion
# ##################################
- alias: system_snapshot_yard
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_g3_flex_yard
      from: 'off'
      to: 'on'
  condition:
    - condition: template
      value_template: "{{(as_timestamp(now())-as_timestamp(state_attr('automation.system_snapshot_yard','last_triggered'))|int) > 10 }}"
  action:
    - service: notify.telegram_cam
      data:
        title: "{{states('sensor.time')}} {{states('sensor.date')}}"
        message: "{{states('sensor.time')}} {{states('sensor.date')}}"
        data:
          photo:
          - url: !secret yard_snap
            caption: "Yard {{states('sensor.time')}} {{states('sensor.date')}}"


# ##################################
# System - Dixy Cam Snapshot on Motion
# ##################################
- alias: system_snapshot_dixy
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_g3_flex_dixy
      from: 'off'
      to: 'on'
  condition:
    - condition: template
      value_template: "{{(as_timestamp(now())-as_timestamp(state_attr('automation.system_snapshot_dixy','last_triggered'))|int) > 10 }}"
  action:
    - service: notify.telegram_cam
      data:
        title: "{{states('sensor.time')}} {{states('sensor.date')}}"
        message: "{{states('sensor.time')}} {{states('sensor.date')}}"
        data:
          photo:
          - url: !secret dixy_snap
            caption: "Dixy {{states('sensor.time')}} {{states('sensor.date')}}"

# ##################################
# System - Street Cam Snapshot on Motion
# ##################################
- alias: system_snapshot_street
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_g3_flex_street
      from: 'off'
      to: 'on'
  condition:
    - condition: template
      value_template: "{{(as_timestamp(now())-as_timestamp(state_attr('automation.system_snapshot_street','last_triggered'))|int) > 10 }}"
  action:
    - service: notify.telegram_cam
      data:
        title: "{{states('sensor.time')}} {{states('sensor.date')}}"
        message: "{{states('sensor.time')}} {{states('sensor.date')}}"
        data:
          photo:
          - url: !secret street_snap
            caption: "Street {{states('sensor.time')}} {{states('sensor.date')}}"


# ##################################
# System - Motion Outside
# ##################################
- alias: system_snaphot_outside
  initial_state: true
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.esp32_domofon_motion
        - binary_sensor.pinhole_camera_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: template
      value_template: "{{(as_timestamp(now())-as_timestamp(state_attr('automation.system_snapshot_outside_esp32','last_triggered'))|int) > 15 }}"
  action:
    - service: notify.telegram_cam
      data:
        title: "{{states('sensor.time')}} {{states('sensor.date')}}"
        message: "{{states('sensor.time')}} {{states('sensor.date')}} "
        data:
          photo:
          - url: !secret door_snap
            caption: "Outside! {{states('sensor.time')}} {{states('sensor.date')}} "