# ##################################
# System - Ubuntu server temp >60
# ##################################
- alias: system_health_temp
  id:  system_health_temp
  initial_state: true
  mode: queued
  max: 5
  max_exceeded: silent
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.ipmi_dimma1_temp
        - sensor.ipmi_dimmb1_temp
        - sensor.ipmi_pch_temp
        - sensor.ipmi_system_temp
      above: 60
      for:
        minutes: 3
  action:
    - service: notify.mobile_app_iphone_12_dtsymbal
      data:
        title: "Внимание!"
        message: "{{ trigger.to_state.attributes.friendly_name }} >60°"
        data:
          push:
            sound:
              name: "default"
              critical: 1
              volume: 1.0
        
    - service: notify.telegram
      data:
        message: "\U0001F525 Внимание! {{ trigger.to_state.attributes.friendly_name }} >60°"

# ##################################
# System - Ubuntu server temp >70
# ##################################
- alias: system_health_cpu_temp_70
  id:  system_health_cpu_temp_70
  initial_state: true
  mode: queued
  max: 2
  max_exceeded: silent
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.ipmi_cpu_temp
        - sensor.processor_temperature
      above: 70
      for:
        minutes: 3
  action:
    - service: notify.mobile_app_iphone_12_dtsymbal
      data:
        title: "Внимание!"
        message: "{{ trigger.to_state.attributes.friendly_name }} >70°"
        data:
          push:
            sound:
              name: "default"
              critical: 1
              volume: 1.0        
        
    - service: notify.telegram
      data:
        message: "\U0001F525 Внимание! {{ trigger.to_state.attributes.friendly_name }} >70°"

# ##################################
# System - Ubuntu server CPU temp >80
# ##################################
- alias: system_health_cpu_temp_80
  id:  system_health_cpu_temp_80
  initial_state: true
  mode: queued
  max: 2
  max_exceeded: silent
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.ipmi_cpu_temp
        - sensor.processor_temperature
      above: 80
      for:
        minutes: 3
  action:
    - service: notify.mobile_app_iphone_12_dtsymbal
      data:
        title: "Внимание!"
        message: "{{ trigger.to_state.attributes.friendly_name }} >80°"
        data:
          push:
            sound:
              name: "default"
              critical: 1
              volume: 1.0        
        
    - service: notify.telegram
      data:
        message: "\U0001F525 Внимание! {{ trigger.to_state.attributes.friendly_name }} >80°"

# ##################################
# System - MDADM status change
# ##################################
- alias: system_health_mdadm_monitor
  id:  system_health_mdadm_monitor
  initial_state: true
  mode: queued
  max: 2
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id:
        - sensor.md0_status
        - sensor.md1_status
  action:
    - service: notify.telegram
      data:
        message: "\U0001f4ab {{ trigger.from_state.attributes.friendly_name }} from {{trigger.from_state.state}} to {{trigger.to_state.state}}"
        
# ##################################
# System - Server HDD Disks Temp
# ##################################
- alias: system_health_hdd_temp_53
  id:  system_health_hdd_temp_53
  initial_state: true
  mode: queued
  max: 5
  max_exceeded: silent
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.main0_temp
        - sensor.main1_temp
        - sensor.main2_temp
        #- sensor.media_temp
        - sensor.temp_temp
      above: 53
  action:
    - service: notify.telegram
      data:
        message: "\U0001f321 Внимание! {{ trigger.to_state.attributes.friendly_name }} >53°!"


# ##################################
# System - Server HDD Disks Temp
# ##################################
# - alias: system_health_hdd_temp
#   initial_state: false
#   trigger:
#     - platform: state
#       entity_id:
#         - sensor.main0_temp
#         - sensor.main1_temp
#         - sensor.main2_temp
#         - sensor.media_temp
#         - sensor.temp_temp
#   condition:
#     - condition: template
#       value_template: "{{ trigger.to_state.state|int(0) % 5 == 0 }}"
#     - condition: template
#       value_template: "{{ trigger.to_state.state|int(0) > 50 }}"
#   action:
#     - service: notify.telegram
#       data:
#         message: "\U0001f321 Внимание! {{ trigger.to_state.attributes.friendly_name }} {{ trigger.to_state.state }}°!"

# ##################################
# System - Server SSD Disks Temp
# ##################################
- alias: system_health_ssd_temp_50
  id:  system_health_ssd_temp_50
  initial_state: true
  mode: queued
  max: 5
  max_exceeded: silent
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.nvme0_temp
        - sensor.nvme1_temp
        - sensor.nvme2_temp
        - sensor.nvme3_temp
        - sensor.boot_temp
      above: 50
      for:
        minutes: 3
  action:
    - service: notify.telegram
      data:
        message: "\U0001f321 Внимание! {{ trigger.to_state.attributes.friendly_name }} >50°!"

# ##################################
# System - Server SSD Disks Temp
# ##################################
- alias: system_health_ssd_temp_55
  id:  system_health_ssd_temp_55
  initial_state: true
  mode: queued
  max: 5
  max_exceeded: silent
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.nvme0_temp
        - sensor.nvme1_temp
        - sensor.nvme2_temp
        - sensor.nvme3_temp
        - sensor.boot_temp
      above: 55
      for:
        minutes: 3
  action:
    - service: notify.telegram
      data:
        message: "\U0001f321 Внимание! {{ trigger.to_state.attributes.friendly_name }} >55°!"
        
# ##################################
# System - Server SSD Disks Temp
# ##################################
- alias: system_health_ssd_temp_60
  id:  system_health_ssd_temp_60
  initial_state: true
  mode: queued
  max: 5
  max_exceeded: silent
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.nvme0_temp
        - sensor.nvme1_temp
        - sensor.nvme2_temp
        - sensor.nvme3_temp
        - sensor.boot_temp
      above: 60
      for:
        minutes: 1
  action:
    - service: notify.telegram
      data:
        message: "\U0001f321 Внимание! {{ trigger.to_state.attributes.friendly_name }} >60°!"

# ##################################
# System - Server Fans stats
# ##################################
- alias: system_health_fans
  id:  system_health_fans
  initial_state: true
  mode: queued
  max: 6
  max_exceeded: silent
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.ipmi_fan1
        - sensor.ipmi_fan2
        - sensor.ipmi_fan3
        - sensor.ipmi_fan4
        - sensor.ipmi_fan5
        - sensor.ipmi_fan6
      below: 250
  action:
    - service: notify.telegram
      data:
        message: "\U0001f300 Внимание! {{ trigger.to_state.attributes.friendly_name }} -> {{ trigger.to_state.state|int(0) }}об!"