# #####################################################################################
#
# SYSTEM - Water Leak
#
# #####################################################################################
# System - Water Leak Detected
# ##################################
- alias: system_water_leak_detected
  id: system_water_leak_detected
  initial_state: true
  mode: queued
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.0x158d00023297e7_moisture
        - binary_sensor.0x158d00023684c2_moisture
        - binary_sensor.0x158d0002373a67_moisture
      from: 'off'
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: >
          {% if trigger.entity_id=="binary_sensor.0x158d00023297e7_moisture"%}light.esp32_node_k_led
          {%elif trigger.entity_id=="binary_sensor.0x158d00023684c2_moisture"%}light.esp32_node_hs_toilet
          {%else%}light.esp32_node_hs_bathroom
          {%endif%}
        effect: 'Red_Alarm'
        brightness_pct: 100
    - service: media_player.volume_set
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: >-
          Вним+ание! Вним+ание! Обнар+ужена ут+ечка вод+ы {% if trigger.entity_id=="binary_sensor.0x158d00023297e7_moisture"%}н+а к+ухне{%elif trigger.entity_id=="binary_sensor.0x158d00023684c2_moisture"%}в туал+ете{%else%}в ванне{%endif%}! Обнар+ужена ут+ечка вод+ы {% if trigger.entity_id=="binary_sensor.0x158d00023297e7_moisture"%}н+а к+ухне{%elif trigger.entity_id=="binary_sensor.0x158d00023684c2_moisture"%}в туал+ете{%else%}в ванне{%endif%}! Вод+а перекрыв+ается!'
    - service: notify.telegram
      data:
        message: >-
          {{'\U000026d4'}}Внимание! Обнаружена утечка воды {% if trigger.entity_id=="binary_sensor.0x158d00023297e7_moisture"%}на кухне{%elif trigger.entity_id=="binary_sensor.0x158d00023684c2_moisture"%}в туалете{%else%}в ванне{%endif%}! Вода перекрывается!
    - service: notify.mobile_app_iphone_12_dtsymbal
      data:
        message: >-
          {{'\U000026d4'}}Внимание! Обнаружена утечка воды {% if trigger.entity_id=="binary_sensor.0x158d00023297e7_moisture"%}на кухне{%elif trigger.entity_id=="binary_sensor.0x158d00023684c2_moisture"%}в туалете{%else%}в ванне{%endif%}! Вода перекрывается!
        data:
          push:
            sound:
              name: "default"
              critical: 1
              volume: 1.0        
    - service: switch.turn_on
      entity_id: switch.esp32_bathroom_node_relay_1
    - delay: '00:00:25'
    - service: switch.turn_off
      entity_id: switch.esp32_bathroom_node_relay_1
    - service: tts.yandextts_say
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Вод+а перекр+ыта! Устран+ите прот+ечку вод+ы {% if trigger.entity_id=="binary_sensor.0x158d00023297e7_moisture"%}н+а к+ухне{%elif trigger.entity_id=="binary_sensor.0x158d00023684c2_moisture"%}в туал+ете{%else%}в ванне{%endif%}!'
    - service: notify.telegram
      data:
        message: >
          {{'\U000026d4'}} Внимание! Вода перекрыта! Устраните протечку воды {% if trigger.entity_id=="binary_sensor.0x158d00023297e7_moisture"%}на кухне{%elif trigger.entity_id=="binary_sensor.0x158d00023684c2_moisture"%}в туалете{%else%}в ванне{%endif%} для включения воды!

# ##################################
# System - Water Leak Off
# ##################################
- alias: system_water_leak_resolved
  id: system_water_leak_resolved
  initial_state: true
  mode: queued
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.0x158d00023297e7_moisture
        - binary_sensor.0x158d00023684c2_moisture
        - binary_sensor.0x158d0002373a67_moisture
      from: 'on'
      to: 'off'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: >
          {% if trigger.entity_id=="binary_sensor.0x158d00023297e7_moisture"%}light.esp32_node_k_led
          {%elif trigger.entity_id=="binary_sensor.0x158d00023684c2_moisture"%}light.esp32_node_hs_toilet
          {%else%}light.esp32_node_hs_bathroom
          {%endif%}  
    - service: media_player.volume_set
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Прот+ечка вод+ы {% if trigger.entity_id=="binary_sensor.0x158d00023297e7_moisture"%}н+а к+ухне{%elif trigger.entity_id=="binary_sensor.0x158d00023684c2_moisture"%}в туал+ете{%else%}в ванне{%endif%} устранен+а! Спас+ибо!'
    - service: notify.telegram
      data:
        message: >
          {{'\U00002705'}} Протечка воды {% if trigger.entity_id=="binary_sensor.0x158d00023297e7_moisture"%}на кухне{%elif trigger.entity_id=="binary_sensor.0x158d00023684c2_moisture"%}в туалете{%else%}в ванне{%endif%} устранена!


# ##################################
# System - Turn Water Off
# ##################################
- alias: system_water_leak_turn_water_off
  id: system_water_leak_turn_water_off
  initial_state: true
  trigger:
    # - platform: state
    #   entity_id: sensor.0x158d00026ea94e_action
    #   to: 'button_1_single'
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: sensor.0x158d00026ea94e_action
        click_type: button_1_single
  action:
    - service: media_player.volume_set
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Зап+ущена процедура выключ+ения вод+ы!'
    - service: notify.telegram
      data:
        message: 'Внимание! Запущена процедура принудительного закрытия воды!'
    - service: switch.turn_on
      entity_id: switch.esp32_bathroom_node_relay_1
    - delay: '00:00:25'
    - service: switch.turn_off
      entity_id: switch.esp32_bathroom_node_relay_1
    - service: media_player.volume_set
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Вод+а в+ыключена!'
    - service: notify.notify
      data:
        title: "Внимание!"
        message: "Принудительное закрытие воды!"
    - service: notify.telegram
      data:
        message: 'Внимание! Вода принидительно закрыта!'

# ##################################
# System - Turn Water On
# ##################################
- alias: system_water_leak_turn_water_on
  id: system_water_leak_turn_water_on
  initial_state: true
  trigger:
    # - platform: state
    #   entity_id: sensor.0x158d00026ea94e_action
    #   to: 'button_2_single'
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: sensor.0x158d00026ea94e_action
        click_type: button_2_single
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.0x158d00023684c2_moisture
        state: 'off'
      - condition: state
        entity_id: binary_sensor.0x158d0002373a67_moisture
        state: 'off'
      - condition: state
        entity_id: binary_sensor.0x158d00023297e7_moisture
        state: 'off'      
  action:
    - service: media_player.volume_set
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Зап+ущена процедура включ+ения вод+ы!'
    - service: notify.telegram
      data:
        message: 'Внимание! Запущена процедура принудительного включения воды!'
    - service: switch.turn_on
      entity_id: switch.esp32_bathroom_node_relay_2
    - delay: '00:00:25'
    - service: switch.turn_off
      entity_id: switch.esp32_bathroom_node_relay_2
    - service: media_player.volume_set
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Вод+а включен+а!'
    - service: notify.telegram
      data:
        message: 'Внимание! Вода принидительно открыта!'
        
# ##################################
# System - Turn Water On_Leak detected
# ##################################
- alias: system_water_leak_turn_water_on_leak_detected
  id: system_water_leak_turn_water_on_leak_detected
  initial_state: true
  trigger:
    # - platform: state
    #   entity_id: sensor.0x158d00026ea94e_action
    #   to: 'button_2_single'
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: sensor.0x158d00026ea94e_action
        click_type: button_2_single      
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.0x158d00023684c2_moisture
        state: 'on'
      - condition: state
        entity_id: binary_sensor.0x158d0002373a67_moisture
        state: 'on'
      - condition: state
        entity_id: binary_sensor.0x158d00023297e7_moisture
        state: 'on' 
  action:
    - service: media_player.volume_set
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Включ+ение вод+ы невозм+ожно! Прот+ечка н+е устранен+а! Дл+я принуд+ительного включ+ения вод+ы нажм+ите кл+авиши Включ+ения и Выключ+ения одноврем+енно!'
    - service: notify.telegram
      data:
        message: 'Внимание! Попытка открыть воду, протечка НЕ устранена!'

# ##################################
# System - Turn Water On_Force
# ##################################
- alias: system_water_leak_turn_water_on_force
  id: system_water_leak_turn_water_on_force
  initial_state: true
  trigger:
    # - platform: state
    #   entity_id: sensor.0x158d00026ea94e_action
    #   to: 'button_3_single'
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: sensor.0x158d00026ea94e_action
        click_type: button_3_single
  action:
    - service: media_player.volume_set
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Прот+ечка вод+ы н+е устранен+а! Зап+ущена процедура принуд+ительного включ+ения вод+ы!'
    - service: notify.telegram
      data:
        message: 'Внимание! Протечка воды не устранена! Запущена процедура принудительного включения воды!'
    - service: switch.turn_on
      entity_id: switch.esp32_bathroom_node_relay_2
    - delay: '00:00:25'
    - service: switch.turn_off
      entity_id: switch.esp32_bathroom_node_relay_2
    - service: media_player.volume_set
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Вод+а включен+а! Прот+ечка н+е устранен+а!'
    - service: notify.telegram
      data:
        message: 'Внимание! Принудительное открытие воды, протечка НЕ устранена!'
        
# ##################################
# System - Water Valves Action
# ##################################
- alias: system_water_valves_action
  id: system_water_valves_action
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.esp32_bathroom_node_relay_1, switch.esp32_bathroom_node_relay_2
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: switch.esp32_bathroom_node_relay_1, switch.esp32_bathroom_node_relay_2
      to: 'off'
      from: 'on'
  action:
    - service: notify.telegram
      data:
        message: >
          {% if trigger.to_state.state == 'on' and 'relay_1' in trigger.to_state.entity_id %}{{'\U000026d4'}} Внимание! Закрытие кранов!
          {% elif trigger.to_state.state == 'off' and 'relay_1' in trigger.to_state.entity_id %}{{'\U00002705'}} Краны закрыты!
          {% elif trigger.to_state.state == 'on' and 'relay_2' in trigger.to_state.entity_id %}{{'\U000026d4'}} Внимание! Открытие кранов!"
          {% elif trigger.to_state.state == 'off' and 'relay_2' in trigger.to_state.entity_id %}{{'\U00002705'}} Краны открыты!
          {%endif%}