# #####################################################################################
#
# SYSTEM - WiFi Devices
#
# #####################################################################################
# System - Critical WiFi Devices state - Unavailable
# ##################################
- alias: system_critical_wifi_devices_unavailable
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: 
        - light.square_led_v
        - light.square_led_s
        - light.round_led_mb
        - light.round_led_k
        - light.round_led_hs
        - light.led_strip_hb
        - light.led_strip_entrance_hb
        - light.bedside_mb
        - fan.humidifier2
        - switch.sonoff_basic_1_relay
        - switch.sonoff_basic_2_relay
        - switch.sonoff_basic_3_relay
        - switch.sonoff_basic_4_relay
        - light.led_color_v
        - light.led_color_mb
        - light.philips_e27_s
        - light.philips_e27_v
        - fan.purifier2s
        - switch.shp2_socket_server_relay
        - switch.gateway_plug_hb
        - light.round_led_secondary_hs
      to: 'unavailable'
      for:
        minutes: 2
  action:
    - service: notify.telegram
      data_template:
        message: "{%if is_state(trigger.entity_id, 'unavailable') %}\U0000274C{%else%}\U00002705{%endif%}{{trigger.from_state.attributes.friendly_name}}: {{trigger.from_state.state}} -> {{trigger.to_state.state}}"

# ##################################
# System - Critical WiFi Devices state - available
# ##################################
- alias: system_critical_wifi_devices_available
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: 
        - light.square_led_v
        - light.square_led_s
        - light.round_led_mb
        - light.round_led_k
        - light.round_led_hs
        - light.led_strip_hb
        - light.led_strip_entrance_hb
        - light.bedside_mb
        - fan.humidifier2
        - switch.sonoff_basic_1_relay
        - switch.sonoff_basic_2_relay
        - switch.sonoff_basic_3_relay
        - switch.sonoff_basic_4_relay
        - light.led_color_v
        - light.led_color_mb
        - light.philips_e27_s
        - light.philips_e27_v
        - fan.purifier2s
        - switch.shp2_socket_server_relay
        - light.round_led_secondary_hs
      from: 'unavailable'
  condition:
    - condition: template
      value_template: "{{(trigger.to_state.last_changed - trigger.from_state.last_changed).total_seconds() > 60 }}"
  action:
    - service: notify.telegram
      data_template:
        message: "{%if is_state(trigger.entity_id, 'unavailable') %}\U0000274C{%else%}\U00002705{%endif%}{{trigger.from_state.attributes.friendly_name}}: {{trigger.from_state.state}} -> {{trigger.to_state.state}}"

# ##################################
# System - Non-Critical WiFi Devices state
# ##################################
- alias: system_noncritical_wifi_devices_state
  initial_state: 'false'
  trigger:
    - platform: state
      entity_id: 
        - light.led_color_v
        - light.led_color_mb
        - light.philips_e27_s
        - light.philips_e27_mb
        - fan.purifier2s
      to: 'unavailable'
  action:
    - service: notify.telegram
      data_template:
        message: "{%if is_state(trigger.entity_id, 'unavailable') %}\U0000274C{%else%}\U00002705{%endif%}{{trigger.from_state.attributes.friendly_name}}: {{trigger.from_state.state}} -> {{trigger.to_state.state}}"
        
# ##################################
# System - BLE Devices state
# ##################################
- alias: system_ble_devices_state
  initial_state: 'false'
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.esp32_ble_tracker_green
        - binary_sensor.esp32_ble_tracker_pink
        - binary_sensor.esp32_ble_tracker_grey
        - binary_sensor.esp32_ble_tracker_white
  action:
    - service: notify.telegram
      data_template:
        message: "{%if is_state(trigger.entity_id, 'unavailable') %}\U0000274C{%else%}\U00002705{%endif%}{{trigger.from_state.attributes.friendly_name}}: {{trigger.from_state.state}} -> {{trigger.to_state.state}}"


# ##################################
# System - BLE Devices tracker restart
# ##################################
- alias: system_ble_device_tracker_restart
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: "/5"
  condition:
    - condition: state
      entity_id: binary_sensor.esp32_ble_tracker_status
      state: 'off'
      for:
        minutes: 3
  action:
    # - service: notify.telegram
    #   data_template:
    #     message: "ble restart"
    - service: switch.turn_off
      entity_id: switch.gateway_plug_entrance_hb_usb
    - delay: "00:00:15"
    - service: switch.turn_on
      entity_id: switch.gateway_plug_entrance_hb_usb
    
      
# ##################################
# System - Water filter MCU restart
# ##################################
- alias: system_water_filter_mcu_restart
  initial_state: 'false'
  trigger:
    - platform: time_pattern
      minutes: "/5"
  condition:
    - condition: state
      entity_id: binary_sensor.esp32_water_filter_status
      state: 'off'
      for:
        minutes: 3
  action:
    # - service: notify.telegram
    #   data_template:
    #     message: "esp32 water filter restart"
    - service: switch.turn_off
      entity_id: switch.sonoff_1000d03987_1
    - delay: "00:00:15"
    - service: switch.turn_on
      entity_id: switch.sonoff_1000d03987_1
      
# ##################################
# System - Critical Switches toggle
# ##################################
- alias: system_critical_switches_toggle
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: 
        - switch.0x158d00023e5812_switch
        - switch.0x158d000392623d_switch
        - switch.esp32_bathroom_node_relay_5
        - switch.sonoff_mini_2_relay
        - switch.gateway_plug_entrance_hb
        - switch.0x158d00039bd56d_switch
        - switch.0x4cf8cdf3c7a9a48_channel_1
        - switch.0x158d0002a36f7f_channel_2
        - switch.sonoff_basic_3_relay
        - switch.sonoff_basic_4_relay
        #- switch.sonoff_1000d03987_1
      to: 'off'
      for:
        seconds: 30
  action:
    - service: switch.turn_on
      data:
        entity_id: "{{ trigger.entity_id }}"
    - service: notify.telegram
      data_template:
        message: "\U00002705 Включение - {{trigger.to_state.attributes.friendly_name}}"