# #####################################################################################
#
# VOVA - General
#
# #####################################################################################
# # Vova - TV Box Off with TV Off
# # ##################################
# - alias: vova_tv_box_off_tv_off
#   initial_state: true
#   trigger:
#     - platform: time_pattern
#       minutes: '/1'
#   condition:
#       - condition: state
#         entity_id: binary_sensor.h96_v
#         state: 'on'
#       - condition: state
#         entity_id: binary_sensor.tv_v
#         state: 'off'
#         for:
#           minutes: 2
#   action:
#     - service: switch.turn_off
#       entity_id: switch.0x158d000290a0bc_switch

# # ##################################
# # Vova - Night mode
# # ##################################
# - alias: vova_night_mode
#   initial_state: false
#   trigger:
#     platform: time
#     at: '23:00:00'
#   action:
#     - service: switch.turn_off
#       entity_id: switch.0x158d000246776f_switch

# # ##################################
# # Vova - TV Box Plug Off with TV Off
# # ##################################
# - alias: vova_tv_box_plug_off_with_tv_off
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.tv_v
#       from: 'off'
#       to: 'on'
#     - platform: state
#       entity_id: binary_sensor.tv_v
#       from: 'on'
#       to: 'off'
#   action:
#     - service: switch.turn_{{states('binary_sensor.tv_v')}}
#       entity_id: switch.0x158d000290a0bc_switch

# ##################################
# Vova - TV Box Restart
# ##################################
- alias: vova_tv_box_restart_sunday_9am
  id: vova_tv_box_restart_sunday_9am
  initial_state: true
  trigger:
    - platform: time
      at: "09:00:00"
  condition:
    - condition: time
      weekday:
        - sun
    - condition: state
      entity_id: input_boolean.security_mode
      state: "off"
  action:
    - service: switch.turn_off
      entity_id: switch.0x158d000290a0bc_switch
    - delay: "00:00:05"
    - service: switch.turn_on
      entity_id: switch.0x158d000290a0bc_switch

# ##################################
# Vova - Purifier on\off
# ##################################
- alias: vova_purifier_toggle
  id: vova_purifier_toggle
  initial_state: true
  mode: queued
  trigger:
    - platform: state
      entity_id: person.sandra
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
  action:
    - service: fan.turn_{{'on' if is_state('person.sandra','home') else 'off'}}
      entity_id: fan.purifier2s
    - condition: template
      value_template: >-
        {{ (is_state('person.sandra','home') and is_state('binary_sensor.breather_v','off'))
        or (not is_state('person.sandra','home') and is_state('binary_sensor.breather_v','on')) }}
    - service: switch.turn_on
      entity_id: switch.digma_ir_v_breather_pwr
