homeassistant:
  name: Dima's Home_Main Server
  external_url: !secret main_external_url
  internal_url: !secret main_internal_url
  latitude: !secret lat
  longitude: !secret long
  elevation: 172
  unit_system: metric
  temperature_unit: C
  currency: RUB
  time_zone: Europe/Moscow
  customize: !include my_config/customize.yaml
  customize_glob: !include my_config/customize_glob.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
      allow_bypass_login: true
    - type: homeassistant
  allowlist_external_dirs:
    - /config
    - /tmp
    - /share

api:

stream:

energy:

usb:

mqtt: !include my_config/mqtt.yaml

http:
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  ip_ban_enabled: false
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    #- 172.30.33.9
    - 172.30.32.0/24
    - 172.30.33.0/24

automation: !include_dir_merge_list my_config/automation
sensor: !include_dir_merge_list my_config/sensors
switch: !include_dir_merge_list my_config/switch
binary_sensor: !include_dir_merge_list my_config/bi-sensor
script: !include_dir_merge_named my_config/scripts

lovelace: !include my_config/lovelace.yaml
timer: !include my_config/timer.yaml
device_tracker: !include my_config/device_tracker.yaml
input_number: !include my_config/input_number.yaml
input_text: !include my_config/input_text.yaml
group: !include my_config/groups.yaml
zone: !include my_config/zone.yaml
counter: !include my_config/counter.yaml
light: !include my_config/light.yaml
yeelight: !include my_config/yeelight.yaml
fan: !include my_config/fan.yaml
person: !include my_config/person.yaml
camera: !include my_config/camera.yaml
notify: !include my_config/notify.yaml
#scene: !include my_config/scene.yaml
shell_command: !include my_config/shell_command.yaml

recorder: !include my_config/recorder.yaml
history: !include my_config/history.yaml
logbook: !include my_config/logbook.yaml
#climate: !include my_config/climate.yaml

telegram_bot: !include my_config/telegram_bot.yaml
weather: !include my_config/weather.yaml
input_select: !include my_config/input_select.yaml
input_boolean: !include my_config/input_boolean.yaml
input_datetime: !include my_config/input_datetime.yaml
tts: !include my_config/tts.yaml
#remote: !include my_config/remote.yaml
panel_iframe: !include my_config/panel_iframe.yaml
proximity: !include my_config/proximity.yaml

#feedreader: !include my_config/feedreader.yaml

utility_meter: !include my_config/utility_meter.yaml
#alert: !include my_config/alert.yaml

#mqtt_statestream: !include my_config/mqtt_statestream.yaml

#number: !include my_config/mqtt_number.yaml

template: !include_dir_merge_list my_config/template

discovery:
zeroconf:
ssdp:
dhcp:
network:

hacs:
  token: !secret github_access_token
  appdaemon: true

#cloud:
mobile_app:
system_health:
config:
hassio:
wake_on_lan:
conversation:
map:
sun:
ios:

system_log:
  fire_event: true

frontend:
  themes: !include_dir_merge_named themes

updater:

# media_source:

#my:

# air_quality:
#   - platform: opensensemap
#     name: OpenSense Map
#     station_id: 5c6409daa100840019d4d0bf

logger:
  default: info
  logs:
    charset_normalizer: error
  filters:
    homeassistant.components.xiaomi_miio:
      - "Timeout fetching Purifier2S data"
  #   homeassistant.core: debug
  #   custom_components.webrtc: debug
  #   custom_components.unifiprotect: debug
#  logs:
#    homeassistant.components.sensor.rest: fatal
#  logs:
#    xiaomi_gateway: debug

# rest_command:
#   kiosk_command:
#     url: !secret rest_url_kiosk_command
#   kiosk_restart:
#     url: !secret rest_kiosk_restart

#twilio:
#  account_sid: !secret twilio_account_sid
#  auth_token: !secret twilio_auth_token

media_player: !include my_config/media_player.yaml

life360:
  interval_seconds: 30
  show_as_state:
    - driving
    - moving

influxdb: !include my_config/influxdb.yaml

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

panel_custom: !include my_config/panel_custom.yaml

##############################################
# Custom Integrations
##############################################
# start_time:

# sonoff:
#   username: !secret sonoff_user
#   password: !secret sonoff_password
#   reload: always
# mode: local
# devices:
#   1000d03987:
#     device_class: switch
#     name: 5v relay

# mosportal:
#   username: !secret mosportal_login
#   password: !secret mosportal_passwd
#   flats:
#     - flat: !secret mosportal_flat
#       paycode: !secret mosportal_paycode

python_script:
xiaomi_gateway3: !include my_config/xiaomi_gateway3.yaml
yandex_smart_home: !include my_config/ya_smart_home.yaml
yandex_station: !include my_config/yandex_station.yaml
yandex_station_intents: !include my_config/yandex_station_intents.yaml