homeassistant:
  name: Dima's Home_Main Server
  external_url: !secret main_external_url
  internal_url: !secret main_internal_url
  latitude: !secret lat
  longitude: !secret long
  elevation: 172
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Moscow
  customize: !include my_config/customize.yaml
  customize_glob: !include my_config/customize_glob.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 172.30.31.0/24
        - 172.30.33.0/24
        - 172.17.0.0/16
        - 192.168.1.0/24
      allow_bypass_login: true
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret api_password
  allowlist_external_dirs:
      - /config
      - /tmp
      - /share
  media_dirs:
      media: /media

api:

stream:

mqtt:
  broker: 192.168.1.30
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant
  client_id: main_ha
  birth_message:
    topic: 'servers/main'
    payload: 'online'
  will_message:
    topic: 'servers/main'
    payload: 'offline'

http:
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  ip_ban_enabled: false
  login_attempts_threshold: 5

automation: !include_dir_merge_list my_config/automation
sensor: !include_dir_merge_list my_config/sensors
switch: !include_dir_merge_list my_config/switch
binary_sensor: !include_dir_merge_list my_config/bi-sensor
script: !include_dir_merge_named my_config/scripts

lovelace: !include my_config/lovelace.yaml
timer: !include my_config/timer.yaml
device_tracker: !include my_config/device_tracker.yaml
input_number: !include my_config/input_number.yaml
input_text: !include my_config/input_text.yaml
group: !include my_config/groups.yaml
zone: !include my_config/zone.yaml
counter: !include my_config/counter.yaml
light: !include my_config/light.yaml
yeelight: !include my_config/yeelight.yaml
fan: !include my_config/fan.yaml
person: !include my_config/person.yaml
camera: !include my_config/camera.yaml
notify: !include my_config/notify.yaml
#scene: !include my_config/scene.yaml
shell_command: !include my_config/shell_command.yaml

recorder: !include my_config/recorder.yaml
history: !include my_config/history.yaml
logbook: !include my_config/logbook.yaml
#climate: !include my_config/climate.yaml

telegram_bot: !include my_config/telegram_bot.yaml
weather: !include my_config/weather.yaml
input_select: !include my_config/input_select.yaml
input_boolean: !include my_config/input_boolean.yaml
input_datetime: !include my_config/input_datetime.yaml
tts: !include my_config/tts.yaml
#remote: !include my_config/remote.yaml
panel_iframe: !include my_config/panel_iframe.yaml
proximity: !include my_config/proximity.yaml

utility_meter: !include my_config/utility_meter.yaml

discovery:
  ignore:
    - yeelight
zeroconf:
ssdp:
dhcp:

hacs:
  token: !secret github_access_token

mobile_app:
system_health:
config:
hassio:
wake_on_lan:
conversation:
map:
sun:
ios:
  push:
    categories:
      - name: Domofon
        identifier: 'domofon_call'
        actions:
          - identifier: 'DOMOFON_OPEN_DOOR'
            title: 'Открыть дверь'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
          - identifier: 'DOMOFON_DONOTOPEN_DOOR'
            title: 'Игнорировать'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'

# ffmpeg:
#   ffmpeg_bin: /usr/bin/ffmpeg

speedtestdotnet:

system_log:
  fire_event: true
  
frontend:
  themes: !include_dir_merge_named themes

updater:
  include_used_components: true

media_source:

logger:
  default: info
  logs:
    homeassistant.event: debug
  #   custom_components.unifiprotect: debug
#  logs:
#    homeassistant.components.sensor.rest: fatal
#  logs:
#    xiaomi_gateway: debug

rest_command:
  kiosk_command:
    url: !secret rest_url_kiosk_command
  kiosk_restart:
    url: !secret rest_kiosk_restart

#twilio:
#  account_sid: !secret twilio_account_sid
#  auth_token: !secret twilio_auth_token

media_player: !include my_config/media_player.yaml
  
life360:
  interval_seconds: 10
  show_as_state:
    - driving
    - moving

influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

python_script:

##############################################
# Custom Integrations
##############################################
start_time:
# circadian_lighting:
#   max_colortemp: 5500 
#   min_colortemp: 3000
#   interval: 300
#   transition: 60

# sonoff:
#   username: !secret sonoff_user
#   password: !secret sonoff_password
#   reload: always
#   mode: local
#   devices:
#     1000d03987:
#       device_class: [switch]
#       name: 5v relay

bessarabov:
  token: !secret bessarabov_main_server_token

#morph_numbers:

xiaomi_gateway3:
  #zigbee_info: msg_received
  #zigbee_console:
  #debug: mqtt
  #debug: true
  # devices:
  #   '0x158d000236bc6d':
  #     occupancy_timeout: 10 
  #   '0x158d0001e05856':
  #     occupancy_timeout: 10 
  #   '0x158d0002b482e9':
  #     occupancy_timeout: 90
  #   '0x158d0001d5995e':
  #     occupancy_timeout: 10
  #   '0x158d0001ae9f61':
  #     occupancy_timeout: 10
  #   '0x158d0002b4729d':
  #     occupancy_timeout: 90
  #   '0x158d0002b48381':
  #     occupancy_timeout: 10
  #   '0x158d0001e53cda':
  #     occupancy_timeout: 90
  #   '0x158d000224f89f':
  #     occupancy_timeout: 10
  #   '0x158d0003140824':
  #     occupancy_timeout: 90
  #   '0x158d0001aea602':
  #     occupancy_timeout: 10
  #   '0x158d0001e54280':
  #     occupancy_timeout: 10 
  #   '0x158d000236bb94':
  #     occupancy_timeout: 10
  #   '0x158d0002b43ad4':
  #     occupancy_timeout: 10


panel_custom:
  - name: panel-redirect
    url_path: config-settings
    sidebar_title: Settings
    sidebar_icon: mdi:hammer-wrench
    module_url: /local/panel-redirect.js
    config:
      target: /config/server_control
  - name: panel-redirect
    url_path: config-integrations
    sidebar_title: Integrations
    sidebar_icon: mdi:puzzle
    module_url: /local/panel-redirect.js
    config:
      target: /config/integrations

# image_processing:
#   - platform: doods
#     url: http://192.168.1.14:8085
#     detector: default
#     scan_interval: 10
#     source:
#       - entity_id: camera.g3_flex_hall
#       - entity_id: camera.g3_flex_window
#       - entity_id: camera.g3_flex_dixy
#       - entity_id: camera.g3_flex_street
#     file_out: "/config/www/{{ camera_entity.split('.')[1] }}.jpg"
#     confidence: 60
#     labels:
#       - name: person
#         confidence: 70
#       - name: car
#         confidence: 50

# image_processing:
#   - platform: tensorflow
#     scan_interval: 99999
#     source:
#       - entity_id: camera.local_file_entr
#       - entity_id: camera.local_file_entr2
#       - entity_id: camera.local_file_hall
#     model:
#       graph: tensorflow/frozen_inference_graph.pb