title: Home - Main Server
views:
  - title: Pinhole
    icon: mdi:camera-wireless-outline
    panel: true
    cards:
      # - type: picture-entity
      #   camera_view: live
      #   aspect_ratio: "16x9"
      #   entity: camera.door_hb
      #   show_name: false
      #   show_state: false
      - type: picture-entity
        camera_view: live
        aspect_ratio: "16x9"
        entity: camera.pinhole #camera.door_hb
        show_name: false
        show_state: false
              
