# ############################################################################
# Security 
# ############################################################################
  - platform: template
    sensors:

      motion_internal:
        friendly_name: Motion Internal
        value_template: "{{ is_state('group.motioninternal','on') }}"
        device_class: motion

      motion:
        friendly_name: Motion
        value_template: "{{ is_state('group.motion','on') }}"
        device_class: motion

      motion_unifi:
        friendly_name: Motion Unifi
        value_template: "{{ is_state('group.motionunifi','on') }}"
        device_class: motion

      doors:
        friendly_name: Doors
        value_template: "{{ is_state('group.doors','on') }}"
        device_class: door

      windows:
        friendly_name: Windows
        value_template: "{{ is_state('group.windows','on') }}"
        device_class: window
