# #####################################################################################
#
# STORAGE - Light
#
# #####################################################################################
# Storage - Auto Light On
# ##################################
- alias: storage_auto_light_on
#  id: storage_auto_light_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0001aea602_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: timer.main_light_delay_st
      state: 'idle'
  action:
    - service: switch.turn_on
      entity_id: switch.0x158d0002a36433_channel_2

# ##################################
# Storage - Main Light On
# ##################################
- alias: storage_main_light_on
#  id: storage_main_light_on
  initial_state: true
  mode: queued
  trigger:
    - platform: state
      entity_id: sensor.0x4cf8cdf3c79546c_action
      to: 'button_2_single'
  condition:
    - condition: state
      entity_id: switch.0x158d0002a36433_channel_2
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.0x158d0002a36433_channel_2

# ##################################
# Storage - Auto Light Off
# ##################################
- alias: storage_light_off
#  id: storage_light_off
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.main_light_st
    - platform: state
      entity_id: sensor.0x4cf8cdf3c79546c_action
      to: 'button_2_single'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: switch.0x158d0002a36433_channel_1
        state: 'on'
      - condition: state
        entity_id: switch.0x158d0002a36433_channel_2
        state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.0x158d0002a36433_channel_1, switch.0x158d0002a36433_channel_2
    - service: timer.cancel
      entity_id: timer.main_light_st

# ##################################
# Storage - Timer Start
# ##################################
- alias: storage_timer_start
#  id: storage_timer_start
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x158d0002a36433_channel_1, switch.0x158d0002a36433_channel_2
      to: 'on'
      from: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_st
    - service: timer.start
      entity_id: timer.main_light_st

# ##################################
# Storage - Timer restart with movement
# ################################## 
- alias: storage_timer_restart
#  id: storage_timer_restart
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0001aea602_motion
      to: 'on'
      from: 'off'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: switch.0x158d0002a36433_channel_1
        state: 'on'
      - condition: state
        entity_id: switch.0x158d0002a36433_channel_2
        state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_st
    - service: timer.start
      entity_id: timer.main_light_st

# ##################################
# Storage - Timer off
# ################################## 
- alias: storage_timer_off
#  id: storage_timer_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x158d0002a36433_channel_2
      to: 'off'
      from: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_st
    - service: timer.cancel
      entity_id: timer.main_light_delay_st
    - service: timer.start
      entity_id: timer.main_light_delay_st


# ##################################
# Storage - Night Off
# ##################################
- alias: storage_night_off
#  id: storage_night_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x158d00023d0b86_action
      to: 'single'
    - platform: state
      entity_id: sensor.0x4cf8cdf3c79546c_action
      to: 'button_1_single'
  action:
    - service: homeassistant.turn_off
      entity_id: 
       - light.esp32_node_k_light
       - light.btf_pixel_strip_top
       - switch.0x158d0002a36433_channel_1
       - switch.0x158d0002a36433_channel_2
       - light.led_strip_hb
       - light.led_strip_entrance_hb
      
# ##################################
# Storage - Dark Mode ON
# ##################################
- alias: storage_light_dark_mode_on
#  id: storage_light_dark_mode_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x158d00023d0b86_action
      to: 'double'
    - platform: state
      entity_id: sensor.0x4cf8cdf3c79546c_action
      to: 'button_1_double'
  condition:
    - condition: state
      entity_id: input_boolean.dark_mode
      state: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dark_mode
    - service: homeassistant.turn_off
      entity_id: 
       - light.esp32_node_k_light
       - light.btf_pixel_strip_top
       - switch.0x158d0002a36433_channel_1
       - switch.0x158d0002a36433_channel_2
       - light.led_strip_hb
       - light.led_strip_entrance_hb

# ##################################
# Storage - Dark Mode OFF
# ##################################
- alias: storage_light_dark_mode_off
#  id: storage_light_dark_mode_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x158d00023d0b86_action
      to: 'double'
    - platform: state
      entity_id: sensor.0x4cf8cdf3c79546c_action
      to: 'button_1_double'
    - platform: state
      entity_id: switch.0x158d000223921b_channel_1, switch.0x158d000253f04a_channel_2
      from: 'on'
      to: 'off'
      for:
        seconds: 5
    - platform: state
      entity_id: switch.0x158d000223921b_channel_1, switch.0x158d000253f04a_channel_2
      from: 'off'
      to: 'on'
      for:
        seconds: 5
  condition:
    - condition: state
      entity_id: input_boolean.dark_mode
      state: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dark_mode