# ############################################################################
# Security 
# ############################################################################
  - binary_sensor: 
      - name: Motion Internal
        state: "{{ is_state('group.motioninternal','on') }}"
        device_class: motion

      - name: Motion
        state: "{{ is_state('group.motion','on') }}"
        device_class: motion

#       - name: Motion Unifi
#         state: "{{ is_state('group.motionunifi','on') }}"
#         device_class: motion

      - name: Doors
        state: "{{ is_state('group.doors','on') }}"
        device_class: door

      - name: Windows
        state: "{{ is_state('group.windows','on') }}"
        device_class: window