# ############################################################################
# Security 
# ############################################################################
  - binary_sensor: 
      - name: Motion Internal
        state: "{{ is_state('group.motioninternal','on') }}"
        device_class: motion

      - name: Motion
        state: "{{ is_state('group.motion','on') }}"
        device_class: motion

#       - name: Motion Unifi
#         state: "{{ is_state('group.motionunifi','on') }}"
#         device_class: motion

      - name: Doors
        state: "{{ is_state('group.doors','on') }}"
        device_class: door

      - name: Windows
        state: "{{ is_state('group.windows','on') }}"
        device_class: window

      - name: Motion 1h
        state: "{{ is_state('group.motioninternal', 'on') }}"
        delay_off: "01:00:00"
        device_class: motion
  
      - name: Someone Home 1h
        state: "{{ is_state('binary_sensor.motion_1h', 'on') or is_state('group.persons', 'home') }}"
        delay_off: "01:00:00"
        device_class: occupancy

      - name: Family Home
        device_class: presence
        state: >
          {{ states('zone.home')|int(0) > 0 or
             states('zone.home_extended')|int(0) > 0 or
             is_state('input_boolean.guest_mode','on') }}

      # - name: Family Home Extended
      #   device_class: presence
      #   state: >
      #     {{ states('zone.home_extended')|int(0) > 0 or 
      #       is_state('input_boolean.guest_mode','on')}}

      - name: Vacation Mode
        state: "{{is_state('input_boolean.security_mode','off')}}"
        delay_on:
          hours: 24
        icon: mdi:palm-tree
          
      - name: Bottom Lock
        device_class: lock
        state: "{{is_state('binary_sensor.0x158d0002a1a4b2_contact','on')}}"
        delay_off:
          seconds: 2
        delay_on:
          seconds: 2
        icon: >
          {% if is_state('binary_sensor.bottom_lock','on') %}
          mdi:lock-open-variant
          {% else %}
          mdi:lock
          {% endif %}

      - name: Top Lock
        device_class: lock
        state: "{{is_state('binary_sensor.0x158d0002b7c2c8_contact','on')}}"
        delay_off:
          seconds: 2
        delay_on:
          seconds: 2
        icon: >
          {% if is_state('binary_sensor.top_lock','on') %}
          mdi:lock-open-variant-outline
          {% else %}
          mdi:lock-outline
          {% endif %}