# #####################################################################################
#
# KITCHEN - General
#
# #####################################################################################
# Kitchen - Sockets on
# ##################################
- alias: kitchen_sockets_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0002b4729d_motion, binary_sensor.0x158d0002b48381_motion
      from: 'off'
      to: 'on'
  condition:
      - condition: template
        value_template: "{{is_state('switch.0x158d00028c9875_switch','off') or is_state('switch.0x158d00028a54e4_switch','off') or is_state('switch.0x158d0001e85086_switch','off')}}"
  action:
    - service: switch.turn_on
      entity_id: switch.0x158d00028c9875_switch, switch.0x158d00028a54e4_switch, switch.0x158d0001e85086_switch

# ##################################
# Kitchen - Weather announcement
# ##################################
- alias: kitchen_weather_announcement
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0002b4729d_motion, binary_sensor.0x158d0002b48381_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      after: '07:20:00'
      before: '07:30:00'
    - condition: template
      value_template: "{{as_timestamp(now()) - as_timestamp(state_attr('automation.kitchen_weather_announcement', 'last_triggered')) > 10*60 }}"
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    - service: script.weather_tts
      data_template:
        entity_id: media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'

# ##################################
# Kitchen - Smoke Detected
# ##################################
- alias: kitchen_smoke_detected
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0002c92f31_smoke
      to: 'on'
  action: 
    - service: notify.telegram
      data_template:
        message: "\U000026d4 Внимание! Сработал датчик дыма!"
        
# ##################################
# Kitchen - Gas Detected
# ##################################
- alias: kitchen_gas_detected
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d00024bcf85_gas
      to: 'on'
  action: 
    - service: notify.telegram
      data_template:
        message: "\U000026d4 Внимание! Сработал датчик газа!"

# ##################################
# Kitchen - Hood Fan
# ##################################
- alias: kitchen_hood_fan
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001e0784e_action
      to: 'button_2_single'
  action:
    - service: switch.toggle
      entity_id: switch.ss5_hood_fan

# ##################################
# Kitchen - Kettle counter
# ##################################
- alias: kitchen_kettle_count
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.mi_kettle_state
      to: 'ON'
  action:
    - service: counter.increment
      entity_id: counter.kettle_k
      
# ##################################
# Kitchen - RO Filter Usage
# ##################################
- alias: kitchen_ro_filter_usage
  initial_state: 'true'
  trigger:
    - platform: time
      at: '00:00:10'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.ro_filter1_usage
        value: "{{ (states('input_number.ro_filter1_usage') | float + states('sensor.water_raw_yesterday') | float) | round(2) }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.ro_filter2_usage
        value: "{{ (states('input_number.ro_filter2_usage') | float + states('sensor.water_raw_yesterday') | float) | round(2) }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.ro_filter3_usage
        value: "{{ (states('input_number.ro_filter3_usage') | float + states('sensor.water_raw_yesterday') | float) | round(2) }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.ro_membrane_usage
        value: "{{ (states('input_number.ro_membrane_usage') | float + states('sensor.water_raw_yesterday') | float) | round(2) }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.ro_postfilter_usage
        value: "{{ (states('input_number.ro_postfilter_usage') | float + states('sensor.water_mineralized_yesterday') | float + states('sensor.water_nonmineralized_yesterday') | float) | round(2)}}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.ro_mineralizer_usage
        value: "{{ (states('input_number.ro_mineralizer_usage') | float + states('sensor.water_mineralized_yesterday') | float) | round(2) }}"
    - service: notify.telegram
      data_template:
        message: "\U0001f4a7 Данные фильтра воды обновлены!"

# ##################################
# Kitchen - Oven notify
# ##################################
- alias: kitchen_oven_notify
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: "/30"
  condition:
    - condition: numeric_state
      entity_id: sensor.esp8266_oven_temp_k
      above: 100
    - condition: state
      entity_id: binary_sensor.motion_k
      state: 'off'
      for: '00:30:00'
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f321 Внимание! Духовка включена ({{states('sensor.esp8266_oven_temp_k')|int}}°C)!"

# ##################################
# Kitchen - TV Plug Off
# ##################################
- alias: kitchen_tv_plug_off
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: "/30"
  condition:
    - condition: time
      after: '02:00:00'
      before: '07:00:00'
    - condition: state
      entity_id: binary_sensor.motion_k
      state: 'off'
      for: '00:15:00'
    - condition: state
      entity_id: switch.0x158d0001e85086_switch
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.0x158d0001e85086_switch

# ##################################
# Kitchen - TV Plug On
# ##################################
- alias: kitchen_tv_plug_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_k
      to: 'on'
  condition:
    - condition: time
      after: '07:00:00'
    - condition: state
      entity_id: switch.0x158d0001e85086_switch
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.0x158d0001e85086_switch
      
# ##################################
# Kitchen - Oven Target Temp
# ##################################
- alias: kitchen_oven_notify_target_temp
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.esp8266_oven_temp_k_oven_status
      to: 'on'
  condition:
    - condition: template
      value_template: "{{ not is_state('input_select.oven_target_temperature', 'Off') }}"
  action:
    - wait_for_trigger:
        - platform: template
          value_template: "{{ states('sensor.esp8266_oven_temp_k')|int > states('input_select.oven_target_temperature')|int }}"
      timeout:
        minutes: 60
      continue_on_timeout: false
    - service: notify.telegram
      data_template:
        message: "\U0001f321 Духовка нагрелась до {{states('sensor.esp8266_oven_temp_k')|int}}°C!"
    - condition: state
      entity_id: binary_sensor.tod_day
      state: 'on'
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data_template: 
        entity_id: media_player.home_mini_k
        message: "Духовка нагрелась до ({{states('sensor.esp8266_oven_temp_k')|int}}°C"