  - sensor:
      - name: Home Status
        unique_id: home_status
        state: >
          {% if is_state('binary_sensor.family_home','on') %}
          Occupied
          {% else %}
          Empty
          {% endif %}
        icon: >
          {% if is_state('binary_sensor.family_home','on') %}
          mdi:home-account
          {% else %}
          mdi:home-outline
          {% endif %}

      - name: People Home
        unique_id: people_home
        state: >-
          {{ expand('group.persons') | selectattr('state', 'in', ['home', 'on'] ) | list | count }}
        icon: >-
          {%- set cnt = expand('group.persons') | selectattr('state', 'in', ['home', 'on'] ) | list | count %}
          {%- if cnt <= 10 %}
            mdi:numeric-{{cnt}}-box
          {%- endif %}
        unit_of_measurement: ea
        attributes:
          names: "{{expand('group.persons') | selectattr('state', 'eq', 'home') | map(attribute='name') | list | join(', ') }}"

#{{ expand('group.persons') | selectattr('state', 'in', ['home', 'on'] ) | list | count }}

      - name: Last Motion
        unique_id: last_motion
        state: " {{iif(expand('group.motioninternal')|count > 0, (expand('group.motioninternal')|sort(attribute='last_changed'))[-1].name, '' , '')}} "

      # - name: Last Motion Time
      #   state: '{{ as_timestamp(states.group.motioninternal.last_changed) | timestamp_custom("%a %d %b %H:%M",true,0) }}'

      - name: Security Devices Last Triggered
        unique_id: security_devices_last_triggered
        state: " {{iif(expand('group.securitydevices')|count > 0, (expand('group.securitydevices')|sort(attribute='last_changed'))[-1].name, '' , '')}} "

      # - name: Security Devices Last Triggered Time
      #   state: '{{ as_timestamp(states.group.securitydevices.last_changed) | timestamp_custom("%a %d %b %H:%M",true,0) }}'

      - name: Door Last Change
        unique_id: door_last_change
        state: " {{iif(expand('group.doors')|count > 0, (expand('group.doors')|sort(attribute='last_changed'))[-1].name, '' , '')}} "
      # - name: Door Last Change Time
      #   state: '{{ (as_timestamp(now())-as_timestamp(states.sensor.door_last_change.last_changed))|timestamp_custom("%H:%M:%S",true,0) }}'

      - name: Window Last Change
        unique_id: windows_last_change
        state: " {{iif(expand('group.windows')|count > 0, (expand('group.windows')|sort(attribute='last_changed'))[-1].name, '' , '')}} "

      # - name: Window Last Chnage Time
      #   state: '{{ (as_timestamp(now())-as_timestamp(states.sensor.window_last_change.last_changed))|timestamp_custom("%H:%M:%S",true,0) }}'
