# #####################################################################################
#
# TOILET - Fan
#
# #####################################################################################
# Toilet Fan - On 10m
# ##################################
- alias: toilet_fan_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001b97111_action
      to: 'single'
    - platform: state
      entity_id: binary_sensor.0x158d000232ddd6_contact
      to: 'on'
      for: 
        minutes: 2
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: switch.0x158d0002a36f7f_channel_1
            state: 'on'
          - condition: state
            entity_id: light.esp32_bathroom_node_light
            state: 'on'
      - condition: state
        entity_id: switch.esp32_bathroom_node_relay_4 #switch.0x00158d0001a248e9_switch_l2 #switch.wall_switch_left_158d0002a36f7f
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.esp32_bathroom_node_relay_4 #switch.0x00158d0001a248e9_switch_l2 #switch.plug_158d0001f54f91

# ##################################
# Toilet Fan - Off
# ##################################
- alias: toilet_fan_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001b97111_action
      to: 'single'
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.fan_t
  condition:
    - condition: state
      entity_id: switch.esp32_bathroom_node_relay_4 #switch.0x00158d0001a248e9_switch_l2 #switch.wall_switch_left_158d0002a36f7f
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.esp32_bathroom_node_relay_4 #switch.0x00158d0001a248e9_switch_l2 #switch.plug_158d0001f54f91
    - service: timer.cancel
      entity_id: timer.fan_t

# ##################################
# Toilet - Fan Timer start on
# ################################## 
- alias: toilet_fan_timer_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.esp32_bathroom_node_relay_4 #switch.0x00158d0001a248e9_switch_l2 #switch.plug_158d0001f54f91
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.fan_t
    - service: timer.start
      entity_id: timer.fan_t

# ##################################
# Toilet - Fan Autostart
# ################################## 
- alias: toilet_fan_auto
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: "/30"
  condition:
    - condition: state
      entity_id: switch.esp32_bathroom_node_relay_4
      state: 'off'
    - condition: template
      value_template: "{{(as_timestamp(now())|int - as_timestamp(states.switch.esp32_bathroom_node_relay_4.last_changed)|int ) > 20*60 }}"
  action:
    - service: switch.turn_on
      entity_id: switch.esp32_bathroom_node_relay_4
