# #####################################################################################
#
# TOILET - Light
#
# #####################################################################################
# Toilet - Timer restart with movement
# ################################## 
- alias: toilet_timer_restart
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0001e54280_motion
      from: 'off'
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: switch.0x158d0002a36f7f_channel_1
        state: 'on'
      - condition: state
        entity_id: light.esp32_bathroom_node_light
        state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_t  
    - service: timer.start
      entity_id: timer.main_light_t

# ##################################
# Toilet - Timer start
# ################################## 
- alias: toilet_timer_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.0x158d0002a36f7f_channel_1
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: light.esp32_bathroom_node_light
      from: 'off'
      to: 'on'
  # condition:
  #   - condition: state
  #     entity_id: timer.main_light_t
  #     state: 'idle'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_t  
    - service: timer.start
      entity_id: timer.main_light_t

# ##################################
# Toilet - Timer pause on
# ################################## 
# - alias: toilet_timer_pause_on
#   initial_state: 'true'
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.0x00158d0001e54280_occupancy
#       from: 'off'
#       to: 'on'
#   condition:
#     - condition: state
#       entity_id: binary_sensor.0x158d000232ddd6_contact
#       state: 'off'
#     - condition: state
#       entity_id: switch.0x00158d0002a36f7f_switch_left
#       state: 'on'
#   action:
#     - service: timer.pause
#       entity_id: timer.main_light_t
#     - service: automation.turn_off
#       entity_id: automation.toilet_timer_restart
    
# ##################################
# Bathroom - Timer pause off
# ################################## 
# - alias: toilet_timer_pause_off
#   initial_state: 'true'
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.0x158d000232ddd6_contact
#       from: 'off'
#       to: 'on'
#   condition:
#     - condition: state
#       entity_id: switch.0x00158d0002a36f7f_switch_left #switch.wall_switch_left_158d0002a36f7f
#       state: 'on'
#   action:
#     - service: timer.start
#       entity_id: timer.main_light_t
#     - service: automation.turn_on
#       entity_id: automation.toilet_timer_restart
    
# ##################################
# Toilet - Auto Light On
# ##################################
- alias: toilet_auto_light_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0001e54280_motion
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.0x158d0001b97111_action
      to: 'single'
    - platform: state
      entity_id: binary_sensor.0x158d000232ddd6_contact
      to: 'on'
      from: 'off'
  condition:
    - condition: state
      entity_id: switch.0x158d0002a36f7f_channel_1
      state: 'off'
    - condition: state
      entity_id: light.esp32_bathroom_node_light
      state: 'off'
  action:
    - service: homeassistant.turn_on
      data_template:
        entity_id: >
          {% if is_state('binary_sensor.tod_day','on') %}switch.0x158d0002a36f7f_channel_1{%else%}light.esp32_bathroom_node_light{%endif%}

# ##################################
# Toilet - Light On
# ##################################
- alias: toilet_light_on
  initial_state: 'false'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001b97111_action
      to: 'single'
    - platform: state
      entity_id: binary_sensor.0x158d000232ddd6_contact
      to: 'on'
      from: 'off'
  condition:
    - condition: state
      entity_id: switch.0x158d0002a36f7f_channel_1
      state: 'off'
    - condition: state
      entity_id: light.esp32_bathroom_node_light
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.0x158d0002a36f7f_channel_1

# ##################################
# Toilet - Auto Light Off
# ##################################
- alias: toilet_auto_off
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: timer.finished
    #   event_data:
    #     entity_id: timer.main_light_t
    - platform: state
      entity_id: timer.main_light_t
      to: 'idle'
      for: '00:00:30'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: switch.0x158d0002a36f7f_channel_1
          state: 'on'
        - condition: state
          entity_id: light.esp32_bathroom_node_light
          state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.0x158d0002a36f7f_channel_1
    - service: light.turn_off
      entity_id: light.esp32_bathroom_node_light
      data:
        transition: 5

# ##################################
# Toilet - Auto Light off - No Motion 2m and Cover Closed
# ##################################
- alias: toilet_auto_light_off_no_motion_cover_closed
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0001e54280_motion
      to: 'off'
      for:
        minutes: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.0x158d000232ddd6_contact
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: switch.0x158d0002a36f7f_channel_1
            state: 'on'
          - condition: state
            entity_id: light.esp32_bathroom_node_light
            state: 'on'
  action:
    - service: timer.finish
      entity_id: timer.main_light_t

# ##################################
# Toilet - Light Toggle with Repeater
# ##################################
- alias: toilet_light_toggle
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001e0a622_action
      to: 'button_2_single'
  action:
    - service_template: homeassistant.turn_{% if is_state('switch.0x158d0002a36f7f_channel_1','on') or is_state('light.esp32_bathroom_node_light','on')%}off{%else%}on{%endif%}
      data_template:
        entity_id: >
          {% if is_state('switch.0x158d0002a36f7f_channel_1','off') and is_state('light.esp32_bathroom_node_light','off') %}
            switch.0x158d0002a36f7f_channel_1
          {% else %}
            switch.0x158d0002a36f7f_channel_1, light.esp32_bathroom_node_light
          {% endif %}

# ##################################
# Toilet - Indicator
# ##################################
- alias: toilet_indicator
  initial_state: 'true'
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d000232ddd6_contact
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.0x158d000232ddd6_contact
      from: 'on'
      to: 'off'
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.0x158d000232ddd6_contact
              state: 'off'
          sequence:
            - service: light.turn_off
              entity_id: light.btf_pixel_strip_toilet
        - conditions:
            - condition: state
              entity_id: binary_sensor.0x158d000232ddd6_contact
              state: 'on'
          sequence:
            - service: light.turn_on
              data_template:
                entity_id: light.btf_pixel_strip_toilet
                effect: 'Color Wipe'
                brightness_pct: 40