# ##################################
# Toilet - Air Freshener Counter
# ##################################
- alias: toilet_air_freshener_counter
#  id: toilet_air_freshener_counter
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.air_freshener_spray
      from: 'on'
      to: 'off'
  action:
    - service: counter.increment
      entity_id: counter.air_freshener_toilet
    - service: input_text.set_value
      data_template:
        entity_id: input_text.air_freshener_last_spray
        value: "{{now().strftime('%d.%m.%Y %H:%M')}}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.air_freshener_last_spray
        value: "{{ as_timestamp(now())|int }}"
    - condition: template
      value_template: "{{ (states('counter.air_freshener_toilet')|int >500) and (states('counter.air_freshener_toilet')|int % 25) == 0 }}"
    - service: notify.telegram
      data_template:
        message: "\U0001f50b Необходимо заменить баллон в освежителе {{states('counter.air_freshener_toilet')}}!"

# ##################################
# Toilet - Air Freshener Spray
# ##################################
- alias: toilet_air_freshener_spray
#  id: toilet_air_freshener_spray
  initial_state: true
  mode: queued
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001b97111_action
      to: 'double'
    - platform: state
      entity_id: binary_sensor.0x158d000232ddd6_contact
      to: 'on'
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: switch.air_freshener_spray
      state: 'off'
    - condition: template
      value_template: "{{(as_timestamp(now())-as_timestamp(state_attr('automation.toilet_air_freshener_spray','last_triggered'))|int) > 15*60 }}"
  action:
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.0x158d000232ddd6_contact
          to: 'off'
          for:
            seconds: 5
      timeout:
        minutes: 20
      continue_on_timeout: false
    - service: switch.turn_on
      entity_id: switch.air_freshener_spray

# ##################################
# Toilet - Air Freshener Battery Alert
# ##################################
- alias: toilet_air_freshener_battery_alert
#  id: toilet_air_freshener_battery_alert
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.esp01_air_freshener_restart
      from: 'unavailable'
      for:
        seconds: 2
  condition:
    - condition: numeric_state
      entity_id: sensor.esp01_air_freshener_vcc
      below: 2.8
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f50b Низкий заряд батареи освежителя {{states('sensor.esp01_air_freshener_vcc')}}в!"

# ##################################
# Toilet - Air Freshener Last Hearbeat
# ##################################
- alias: toilet_air_freshener_last_hearbeat
#  id: toilet_air_freshener_last_hearbeat
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.esp01_air_freshener_restart
    #   to: 'unavailable'
    # - platform: state
    #   entity_id: switch.esp01_air_freshener_restart
    #   from: 'off'
  action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.air_freshener_last_heartbeat
        value: "{{ as_timestamp(states.sensor.esp01_air_freshener_vcc.last_updated)|timestamp_custom('%d.%m.%Y %H:%M',true) }}"

# ##################################
# Toilet - Air Freshener Hourly
# ##################################
- alias: toilet_air_freshener_bi_hourly
#  id: toilet_air_freshener_bi_hourly
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: "/2"
  condition:
    - condition: template
      value_template: "{{(as_timestamp(now())|int - states('input_number.air_freshener_last_spray')|int ) > 2*60*60 }}"
    - condition: state
      entity_id: binary_sensor.0x158d000232ddd6_contact
      state: 'off'
    - condition: state
      entity_id: binary_sensor.tod_day
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.air_freshener_spray

# ##################################
# System - Air freshener offline
# ##################################
- alias: system_air_freshener_offline
#  id: system_air_freshener_offline
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.esp01_air_freshener_status
      to: 'unavailable'
      for:
        minutes: 16
  action: 
    - service: notify.telegram
      data_template:
        message: "\U0001f32c Освежитель воздуха не выходит на связь!"

# # ##################################
# # Toilet - Heater Control
# # ##################################
- alias: toilet_heater_control
#  id: toilet_heater_control
  initial_state: true
  trigger:
    - platform: template
      value_template: "{{ not (6>=now().hour|int >=0 or is_state('input_boolean.security_mode','on') or (is_state('binary_sensor.0x158d0001ef2ffc_contact','on') and (as_timestamp(now())-as_timestamp(states.binary_sensor['0x158d0001ef2ffc_contact'].last_changed) > 10*60))) }}"
  action: 
    - service: climate.turn_{% if not (6>=now().hour|int >=0 or is_state('input_boolean.security_mode','on') or (is_state('binary_sensor.0x158d0001ef2ffc_contact','on') and (as_timestamp(now())-as_timestamp(states.binary_sensor['0x158d0001ef2ffc_contact'].last_changed) > 10*60))) %}on{%else%}off{%endif%}
      entity_id: climate.sonoff_pow_r2_2_heater