# ##################################
# Toilet - Air Freshener Counter
# ##################################
- alias: toilet_air_freshener_counter
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.air_freshener_spray
      from: 'on'
      to: 'off'
  action:
    - service: counter.increment
      entity_id: counter.air_freshener_toilet
    - service: input_text.set_value
      data_template:
        entity_id: input_text.air_freshener_last_spray
        value: "{{now().strftime('%d.%m.%Y %H:%M')}}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.air_freshener_last_spray
        value: "{{ as_timestamp(now())|int }}"

# ##################################
# Toilet - Air Freshener Spray
# ##################################
- alias: toilet_air_freshener_spray
  initial_state: 'true'
  mode: restart
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001b97111_action
      to: 'double'
    - platform: state
      entity_id: binary_sensor.0x158d000232ddd6_contact
      to: 'on'
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: switch.air_freshener_spray
      state: 'off'
    - condition: template
      value_template: "{{(as_timestamp(now())-as_timestamp(state_attr('automation.toilet_air_freshener_spray','last_triggered'))|int) > 15*60 }}"
  action:
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.0x158d000232ddd6_contact
          to: 'off'
          for:
            seconds: 5
      timeout:
        minutes: 20
      continue_on_timeout: false
    - service: switch.turn_on
      entity_id: switch.air_freshener_spray

# ##################################
# Toilet - Air Freshener Battery Alert
# ##################################
- alias: toilet_air_freshener_battery_alert
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.esp01_air_freshener_restart
      from: 'unavailable'
      for:
        seconds: 2
  condition:
    - condition: numeric_state
      entity_id: sensor.esp01_air_freshener_vcc
      below: 3
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f50b Низкий заряд батареи освежителя {{states('sensor.esp01_air_freshener_vcc')}}в!"

# ##################################
# Toilet - Air Freshener Last Hearbeat
# ##################################
- alias: toilet_air_freshener_last_hearbeat
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.esp01_air_freshener_restart
    #   to: 'unavailable'
    # - platform: state
    #   entity_id: switch.esp01_air_freshener_restart
    #   from: 'off'
  action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.air_freshener_last_heartbeat
        value: "{{ as_timestamp(states.sensor.esp01_air_freshener_vcc.last_updated)|timestamp_custom('%d.%m.%Y %H:%M',true) }}"

# ##################################
# Toilet - Air Freshener Hourly
# ##################################
- alias: toilet_air_freshener_bi_hourly
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      hours: "/2"
  condition:
    - condition: template
      value_template: "{{(as_timestamp(now())|int - states('input_number.air_freshener_last_spray')|int ) > 2*60*60 }}"
    - condition: state
      entity_id: binary_sensor.0x158d000232ddd6_contact
      state: 'off'
    - condition: state
      entity_id: binary_sensor.tod_day
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.air_freshener_spray

# ##################################
# Toilet - cold water condensate
# ##################################
- alias: toilet_cold_water_condensate
  initial_state: 'false'
  trigger:
    - platform: template
      value_template: "{{ (states('sensor.dewpoint_t')|float - states('sensor.esp32_bathroom_node_cold_pipe')|float ) > 2 }}"
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f4a6 Внимание! Возможно образование конденсата в туалете!"

# ##################################
# System - Air freshener offline
# ##################################
- alias: system_air_freshener_offline
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.esp01_air_freshener_status
      to: 'unavailable'
      for:
        minutes: 16
  action: 
    - service: notify.telegram
      data_template:
        message: "\U0001f32c Освежитель воздуха не выходит на связь!"

# # ##################################
# # Toilet - Heater Auto On
# # ##################################
# - alias: toilet_heater_auto_on
#   initial_state: 'true'
#   trigger:
#     - platform: time_pattern
#       minutes: '/30'
#   condition:
#     - condition: numeric_state
#       entity_id: sensor.0x158d0001e58754_temperature
#       below: 25
#   action: 
#     - service: switch.turn_on
#       entity_id: switch.sonoff_basic_1_relay
  
# # ##################################
# # Toilet - Heater timer
# # ##################################
# - alias: toilet_heater_timer_start
#   initial_state: 'true'
#   trigger:
#     - platform: state
#       entity_id: switch.sonoff_basic_1_relay
#       to: 'on'
#   action:
#     - service: timer.cancel
#       entity_id: timer.heater_t
#     - service: timer.start
#       entity_id: timer.heater_t 

# # ##################################
# # Toilet - Heater Auto Off
# # ##################################
# - alias: toilet_heater_auto_off
#   initial_state: 'true'
#   trigger:
#     - platform: event
#       event_type: timer.finished
#       event_data:
#         entity_id: timer.heater_t
#   action:
#     - service: switch.turn_off
#       entity_id: switch.sonoff_basic_1_relay