# #####################################################################################
#
# MASTER BEDROOM - breather
#
# #####################################################################################
# Master Bedroom- breather On
# ################################## 
- alias: master_bedroom_breather_on
#  id: master_bedroom_breather_on
  initial_state: false
  trigger:
    - platform: time_pattern
      minutes: "/5"
  condition:
    - condition: state
      entity_id: binary_sensor.family_home
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.z19_co2_mb
      above: 1000
    - condition: state
      entity_id: binary_sensor.breather_mb
      state: 'off'
    - condition: state
      entity_id: binary_sensor.0x158d000200ad58_contact
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.digma_ir_mb_breather_pwr

# ##################################
# Master Bedroom- breather Off
# ################################## 
- alias: master_bedroom_breather_off
#  id: master_bedroom_breather_off
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: "/5"
  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
        - condition: numeric_state
          entity_id: sensor.z19_co2_mb
          below: 800
        - condition: state
          entity_id: binary_sensor.breather_mb
          state: 'on'
      - condition: and
        conditions:
        - condition: state
          entity_id: binary_sensor.0x158d000200ad58_contact
          state: 'on'
        - condition: state
          entity_id: binary_sensor.breather_mb
          state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.digma_ir_mb_breather_pwr
      
# ##################################
# Master Bedroom- breather Aurtomation Status Publish
# ################################## 
- alias: master_bedroom_breather_automation_status_publish
#  id: master_bedroom_breather_automation_status_publish
  initial_state: true
  mode: queued
  trigger:
    - platform: state
      entity_id:
        - automation.master_bedroom_breather_off
        - automation.master_bedroom_breather_on
  action:
    - service: mqtt.publish
      data:
        topic: servers/main_states/automation/breather_mb
        payload: "{{('1' if is_state('automation.master_bedroom_breather_on','on') else '0')|int}}{{('1' if is_state('automation.master_bedroom_breather_off','on') else '0')|int}}"
        retain: true
      