# #####################################################################################
#
# MASTER BEDROOM - Lights
#
# #####################################################################################
# MB Table Lamp (Yeelight White)
# ##################################
- alias: master_bedroom_table_lamp
  id: master_bedroom_table_lamp
  initial_state: true
  mode: single
  max_exceeded: silent
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: sensor.0x158d00023d3116_action
  condition:
    - condition: template
      value_template: "{{ states('light.led_white_mb') in ['on','off'] }}"
    - condition: template
      value_template: "{{ is_state_attr(this.entity_id, 'current',0) }}"
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.click_type == 'single' }}"
          sequence:
            - service: light.toggle
              entity_id: light.led_white_mb
        - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.click_type == 'double' }}"
          sequence:
            - service: light.turn_on
              entity_id: light.led_white_mb
              data:
                brightness_pct: 100
                kelvin: 5000
        - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.click_type == 'hold' }}"
          sequence:
            - service: light.turn_on
              entity_id: light.led_white_mb
              data:
                brightness_pct: 5
                kelvin: 3000

# ##################################
# Master Bedroom Main Lamp (Xiaomi Round LED)
# ##################################
- alias: master_bedroom_main_lamp_right_button
  id: master_bedroom_main_lamp_right_button
  initial_state: true
  mode: single
  max_exceeded: silent
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: sensor.0x158d00013e6aa5_action
        click_type: button_2_single
  condition:
    - condition: template
      value_template: "{{ states('light.round_led_mb') in ['on','off'] }}"
    - condition: template
      value_template: "{{ is_state_attr(this.entity_id, 'current',0) }}"
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.round_led_mb_nightlight
              state: 'on'
            - condition: state
              entity_id: light.round_led_mb
              state: 'off'
          sequence:
            - service: yeelight.set_mode
              data:
                entity_id: light.round_led_mb
                mode: normal
            - service: light.turn_on
              entity_id: light.round_led_mb
              data:
                brightness_pct: 90
                kelvin: 5000
        - conditions:
            - condition: state
              entity_id: light.round_led_mb
              state: 'off'
            - condition: state
              entity_id: binary_sensor.round_led_mb_nightlight
              state: 'off'
          sequence:
            - service: light.turn_on
              entity_id: light.round_led_mb
              data:
                brightness_pct: 90
                kelvin: 5000
        - conditions:
            - condition: state
              entity_id: light.round_led_mb
              state: 'on'
          sequence:
            - service: light.turn_off
              entity_id: light.round_led_mb
                

# ##################################
# Master Bedroom Main Lamp (Xiaomi Round LED) - Full
# ##################################
- alias: master_bedroom_main_lamp_right_button_full
  id: master_bedroom_main_lamp_right_button_full
  initial_state: true
  mode: single
  max_exceeded: silent
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: sensor.0x158d00013e6aa5_action
        click_type: button_2_double
  condition:
    - condition: template
      value_template: "{{ states('light.round_led_mb') in ['on','off'] }}"
  action:
    - service: light.turn_on
      entity_id: light.round_led_mb
      data:
        brightness_pct: 90
        kelvin: 5000

# ##################################
# Master Bedroom Main Lamp (Xiaomi Round LED)
# ##################################
- alias: master_bedroom_main_lamp_left_button
  id: master_bedroom_main_lamp_left_button
  initial_state: true
  mode: single
  max_exceeded: silent
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: sensor.0x158d00013e6aa5_action
        click_type: button_1_single
  condition:
    - condition: template
      value_template: "{{ states('light.round_led_mb') in ['on','off'] }}"
    - condition: template
      value_template: "{{ is_state_attr(this.entity_id, 'current',0) }}"
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.round_led_mb_nightlight
              state: 'on'
            - condition: state
              entity_id: light.round_led_mb
              state: 'off'
          sequence:
            - service: yeelight.set_mode
              data:
                entity_id: light.round_led_mb
                mode: normal
            - service: light.turn_on
              entity_id: light.round_led_mb
              data:
                brightness_pct: 30
                kelvin: 3000
        - conditions:
            - condition: state
              entity_id: light.round_led_mb
              state: 'off'
            - condition: state
              entity_id: binary_sensor.round_led_mb_nightlight
              state: 'off'
          sequence:
            - service: light.turn_on
              entity_id: light.round_led_mb
              data:
                brightness_pct: 30
                kelvin: 3000
        - conditions:
            - condition: state
              entity_id: light.round_led_mb
              state: 'on'
          sequence:
            - service: light.turn_off
              entity_id: light.round_led_mb

# ##################################
# Master Bedroom - Round LED Restart
# ##################################
- alias: master_bedroom_round_led_restart
  id: master_bedroom_round_led_restart
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: "/1"
    # - platform: state
    #   entity_id: light.round_led_mb
    #   to: "unavailable"
    #   for:
    #     minutes: 2
    # - platform: numeric_state
    #   entity_id: sensor.ha_uptime
    #   above: 0
    #   below: 2
  condition:
    - condition: state
      entity_id: light.round_led_mb
      state: "unavailable"
      for:
        minutes: 2
    - condition: template
      value_template: "{{ is_state_attr(this.entity_id, 'current',0) }}"
    - condition: state
      entity_id: switch.round_led_mb_restart_key
      state: 'on'
  action:
    - repeat:
        while:
          - condition: state
            entity_id: light.round_led_mb
            state: "unavailable"
          - condition: template
            value_template: "{{ repeat.index <= 5 }}"
        sequence:
          - service: switch.turn_off
            entity_id: switch.sonoff_basic_3_relay
          - delay:
              seconds: 15
          - service: switch.turn_on
            entity_id: switch.sonoff_basic_3_relay
          - service: notify.telegram
            data:
              message: "\U0001f6a8 Round LED MB restart done({{repeat.index}})!"
          - delay:
              seconds: 30
    - condition: state
      entity_id: light.round_led_mb
      state: 'unavailable'
    - service: notify.telegram
      data:
        message: "\U0001f6a8 Round LED MB restart unsuccessful!"
    - service: switch.turn_off
      entity_id: switch.round_led_mb_restart_key

# ##################################
# Master Bedroom - Main Light Auto Restart Key Toggle
# ##################################
- alias: master_bedroom_main_lamp_restart_key_toggle
  id: master_bedroom_lamp_restart_key_toggle
  initial_state: true
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: light.round_led_mb
      from: 'unavailable'
  action:
    - service: switch.turn_on
      entity_id: switch.round_led_mb_restart_key

# ##################################
# Master Bedroom - Turn Lamp Switch On if Off
# ##################################
- alias: master_bedroom_main_lamp_switch_on_if_off
  id: master_bedroom_main_lamp_switch_on_if_off
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: sensor.0x158d00013e6aa5_action
        click_type: button_2_single
  condition:
    - condition: state
      entity_id: switch.sonoff_basic_3_relay
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_basic_3_relay

# ##################################
# Master Bedroom - Timer restart with movement
# ##################################
- alias: master_bedroom_timer_restart
  id: master_bedroom_timer_restart
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0001e53cda_motion
      from: 'off'
      to: 'on'  
    # - platform: event
    #   event_type: xiaomi_aqara.motion
    #   event_data:
    #     entity_id: binary_sensor.0x158d0001e53cda_motion
  condition:
    - condition: state
      entity_id: light.round_led_mb
      state: "on"
  action:
    - service: timer.cancel
      entity_id: timer.main_light_mb
    - service: timer.start
      entity_id: timer.main_light_mb

# ##################################
# Master Bedroom - Timer off
# ##################################
- alias: master_bedroom_timer_off
  id: master_bedroom_timer_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.round_led_mb
      to: "off"
      from: "on"
  action:
    - service: timer.cancel
      entity_id: timer.main_light_mb

# ##################################
# Master Bedroom - Timer start on light on
# ##################################
- alias: master_bedroom_timer_on
  id: master_bedroom_timer_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.round_led_mb
      to: "on"
      from: "off"
  action:
    - service: timer.cancel
      entity_id: timer.main_light_mb
    - service: timer.start
      entity_id: timer.main_light_mb

# # ##################################
# # Master Bedroom - Auto Light Off
# # ##################################
# - alias: master_bedroom_auto_light_off
#   initial_state: true
#   trigger:
#     - platform: event
#       event_type: timer.finished
#       event_data:
#         entity_id: timer.main_light_mb
#   # condition:
#   #   - condition: state
#   #     entity_id: binary_sensor.tod_day
#   #     state: 'on'
#   action:
#     - service: light.turn_off
#       entity_id: light.round_led_mb
#       data:
#         transition: 30

# ##################################
# Master Bedroom - Auto Light On
# ##################################
# - alias: master_bedroom_auto_light_on
#   initial_state: true
#   trigger:
#     - platform: event
#       event_type: xiaomi_aqara.motion
#       event_data:
#         entity_id: binary_sensor.motion_sensor_158d0001e53cda
#   condition:
#     condition: and
#     conditions:
#       - condition: state
#         entity_id: light.round_led_mb
#         state: 'off'
#       - condition: state
#         entity_id: binary_sensor.tod_day
#         state: 'on'
#       - condition: state
#         entity_id: sun.sun
#         state: below_horizon
#   action:
#     - service: light.turn_on
#       entity_id: light.round_led_mb

# ##################################
# Master Bedroom - Auto Ambilight On
# ##################################
# - alias: master_bedroom_auto_ambilight_light
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: light.round_led_mb
#   action:
#     - service: script.turn_on
#       data:
#         entity_id: script.master_bedroom_ambilight_{{ states('light.round_led_mb') | lower }}

# ##################################
# Master Bedroom Table Lamp (Yeelight Color E27)
# ##################################
- alias: master_bedroom_color_table_lamp
  id: master_bedroom_color_table_lamp
  initial_state: true
  mode: single
  max_exceeded: silent
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: sensor.0x158d0001ef61be_action
  condition:
    - condition: template
      value_template: "{{ states('light.led_color_mb') in ['on','off'] }}"
    - condition: template
      value_template: "{{ is_state_attr(this.entity_id, 'current',0) }}"
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.click_type == 'single' }}"
          sequence:
            - service: light.toggle
              entity_id: light.led_color_mb
        - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.click_type == 'double' }}"
          sequence:
            - service: light.turn_on
              entity_id: light.led_color_mb
              data:
                brightness_pct: 100
                kelvin: 5000
        - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.click_type == 'hold' }}"
          sequence:
            - service: light.turn_on
              entity_id: light.led_color_mb
              data:
                brightness_pct: 5
                kelvin: 3000
