# #####################################################################################
#
# HALL BIG
#
# #####################################################################################
# Hall Big - Domofon Incoming Call
# ##################################
- alias: hall_big_domofon_incoming_call
  initial_state: 'true'
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.esp32_domofon_incomingcall
      to: 'on'
  action:
    - service: notify.telegram_cam
      data:
        title: "{{states('sensor.time')}} {{states('sensor.date')}}"
        message: "{{states('sensor.time')}} {{states('sensor.date')}}"
        data:
          photo:
          - url: !secret window_snap
            caption: "Звонок в домофон {{states('sensor.time')}} {{states('sensor.date')}}"
    - service: notify.mobile_app_iphone_8_dtsymbal
      data:
        message: "Звонок в домофон!"
        data:
          push:
            badge: 0
            category: "domofon_call"
    - service: script.turn_on
      entity_id: script.domofon_script
    - delay: '00:15:00'
    - service: script.turn_on
      entity_id: script.domofon_check

# ##################################
# Hall Big - Domofon Auto Open On Arrival
# ##################################
- alias: hall_big_domofon_auto_open_on_arrival
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: person.dima
      to: 'home'
    - platform: state
      entity_id: person.sandra
      to: 'home'
    - platform: state
      entity_id: person.vova
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.domofon_auto_open_once
        state: 'off'
      - condition: state
        entity_id: input_boolean.domofon_auto_open
        state: 'off'
      - condition: template
        value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  action:
    - service: notify.telegram
      data_template:
        message: >
          {% if trigger.from_state.attributes.friendly_name == "Dima" %} {{"\U0001F9D4"}} Дима прибыл домой!
          {% elif trigger.from_state.attributes.friendly_name == "Sandra" %} {{"\U0001F467"}} Саша прибыла домой!
          {% elif trigger.from_state.attributes.friendly_name == "Vova" %} {{"\U0001F471"}} Вова прибыл домой!
          {%endif%}
    - service_template: >
        {% if trigger.from_state.attributes.friendly_name != "Babayka"%} notify.telegram_{{ trigger.from_state.attributes.friendly_name|lower }}
        {%else%} script.noop
        {%endif%}
      data_template:
        message: "\U0001F4DE Домофон: Автооткрытие включено на 15мин! {% if is_state('binary_sensor.bottom_lock','off') or is_state('binary_sensor.upper_lock','off') %}Закрыт{%if is_state('binary_sensor.bottom_lock','off') %} нижний{%endif%}{%if is_state('binary_sensor.upper_lock','off')%} и верхний{%endif%} замок{%endif%}"
    - service: script.turn_on
      entity_id: script.domofon_mute_toggle
    - service: script.turn_on
      entity_id: script.domofon_auto_open_once_toggle
    - delay: '00:15:00'
    - service: script.turn_on
      entity_id: script.domofon_check

# ##################################
# Hall Big - Domofon auto off on door open\close
# ##################################
- alias: hall_big_domofon_off_on_door open_close
  initial_state: 'true'
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0001e5d6be_contact
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.domofon_auto_open_once
      state: 'on'
    - condition: state
      entity_id: input_boolean.domofon_mute
      state: 'on'
  action:
    - delay: '00:10:00'
    - service: script.turn_on
      entity_id: script.domofon_check

# ##################################
# Hall Big - Domofon open door from iphone
# ##################################
- alias: hall_big_domofon_open_iphone
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: DOMOFON_OPEN_DOOR
  action:
    service: script.turn_on
    entity_id: script.domofon_open_door

# ##################################
# Hall big - Domofon Open Button
# ##################################
- alias: hall_big_domofon_button_open
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0002f8dd54_action
      to: 'single'
  action:
    - service: switch.turn_on
      entity_id: switch.esp32_domofon_open
    - service: notify.telegram
      data_template:
        message: "\U0001f518 Домофон открыт вручную!"
        data:
          photo:
            - url: !secret entrance_snap
              caption: "\U0001f518 Домофон открыт вручную!"


# ##################################
# Hall big - Domofon Auto Open Once
# ##################################
- alias: hall_big_domofon_button_auto_open_once
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0002f8dd54_action
      to: 'double'
  action:
    - service: script.turn_on
      entity_id: script.domofon_auto_open_once_toggle
      
# ##################################
# Hall big - Domofon Auto Open 
# ##################################
- alias: hall_big_domofon_button_auto_open
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0002f8dd54_action
      to: 'hold'
  action:
    - service: script.turn_on
      entity_id: script.domofon_auto_open_toggle