# #####################################################################################
#
# HALL BIG
#
# #####################################################################################
# Hall Big - Doorbell
# ##################################
- alias: hall_big_doorbell
#  id: hall_big_doorbell
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.sonoff_mini_1_switch
      from: 'off'
      to: 'on'
  action:
    - service: notify.telegram_family
      data:
        title: Doorbell photo
        message: "\U0001f514 Внимание! Кто-то звонит в дверь!"
        data:
          photo:
          - url: !secret door_snap #http://192.168.1.14:8123{{state_attr('camera.door_hb','entity_picture')}}
            caption: "\U0001f514 Внимание! Кто-то звонит в дверь! {{states('sensor.time')}} {{states('sensor.date')}}"
    # - service: script.turn_on
    #   data:
    #     entity_id: >
    #       {% if is_state('input_boolean.silent_mode','off') %}script.doorbell_ring
    #       {%else%}script.noop
    #       {%endif%}