# #####################################################################################
#
# HALL BIG
#
# #####################################################################################
# Hall Big - Fridge open for more than 
# ##################################
- alias: hall_big_fridge_not_closed_5m
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d000253722b_contact
      from: 'off'
      to: 'on'
      for:
        minutes: 5
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F441 Внимание! Холодильник не закрыт!"
    # - condition: state
    #   entity_id: binary_sensor.tod_day
    #   state: 'on'
    # - service: media_player.volume_set
    #   data_template:
    #     entity_id: media_player.{{states('input_select.main_audio_out')|lower}}
    #     volume_level: '{{states("input_number.main_volume")|float}}'
    # - service: tts.yandextts_say
    #   data_template:
    #     entity_id: media_player.{{states('input_select.main_audio_out')|lower}}
    #     message: 'Вним+ание! Холод+ильник н+е закр+ыт!'

            
####################################
# Hall Big - Freezer open for more than 
####################################
- alias: hall_big_freezer_not_closed_5m
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d000252acba_contact
      from: 'off'
      to: 'on'
      for:
        minutes: 5
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F441 Внимание! Морозильник не закрыт!"
    # - condition: state
    #   entity_id: binary_sensor.tod_day
    #   state: 'on'
    # - service: media_player.volume_set
    #   data_template:
    #     entity_id: media_player.{{states('input_select.main_audio_out')|lower}}
    #     volume_level: '{{states("input_number.main_volume")|float}}'
    # - service: tts.yandextts_say
    #   data_template:
    #     entity_id: media_player.{{states('input_select.main_audio_out')|lower}}
    #     message: 'Вним+ание! Мороз+ильник н+е закр+ыт!'

# # ##################################
# # Hall big - Fridge door open time
# # ##################################
# - alias: hall_big_fridge_door_open_time
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.0x158d000253722b_contact
#       from: 'off'
#       to: 'on'
#   action:
#     - service: input_number.set_value
#       data_template:
#         entity_id: input_number.fridge_door_open_time
#         value: "{{ as_timestamp(now())|int }}"

# # ##################################
# # Hall big - Fridge door closed after 5 mins
# # ##################################
# - alias: hall_big_fridge_door_closed
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.0x158d000253722b_contact
#       from: 'on'
#       to: 'off'
#   condition:
#     - condition: template
#       value_template: "{{ (as_timestamp(now())|int - states('input_number.fridge_door_open_time')|int)  > 310 }}"
#   action:
#   - service: notify.telegram
#     data_template:
#       message: "Холодильник успешно закрыт спустя {{ ((as_timestamp(now())|int - states('input_number.fridge_door_open_time')|int)/60)|int }}м."

# # ##################################
# # Hall big - Freezer door open time
# # ##################################
# - alias: hall_big_freezer_door_open_time
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.0x158d000252acba_contact
#       from: 'off'
#       to: 'on'
#   action:
#     - service: input_number.set_value
#       data_template:
#         entity_id: input_number.freezer_door_open_time
#         value: "{{ as_timestamp(now())|int }}"
        
# # ##################################
# # Hall big - Freezer door closed after 5 mins
# # ##################################
# - alias: hall_big_freezer_door_closed
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.0x158d000252acba_contact
#       from: 'on'
#       to: 'off'
#   condition:
#     - condition: template
#       value_template: "{{ ( as_timestamp(now())|int - states('input_number.freezer_door_open_time')|int)  > 310  }}"
#   action:
#   - service: notify.telegram
#     data:
#       message: "Морозилка успешно закрыта спустя {{ ((as_timestamp(now())|int - states('input_number.freezer_door_open_time')|int)/60)|int }}м."
      
# ##################################
# Hall big - Fridge temp alarm
# ##################################
- alias: hall_big_fridge_temp_alarm
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: "/10"
  condition:
    - condition: numeric_state
      entity_id: sensor.0x158d0002461e5b_temperature
      above: 15
  action:
  - service: notify.telegram
    data:
      message: "\U0001f321 Внимание! Температура в холодильнике {{states('sensor.0x158d0002461e5b_temperature')|int}}°C!"
      
# ##################################
# Hall big - Freezer temp alarm
# ##################################
- alias: hall_big_freezer_temp_alarm
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: "/10"
  condition:
    - condition: numeric_state
      entity_id: sensor.0x158d000237167c_temperature
      above: 0
  action:
  - service: notify.telegram
    data:
      message: "\U0001f321 Внимание! Температура в морозилке {{states('sensor.0x158d000237167c_temperature')|int}}°C!"