# #####################################################################################
#
# HALL BIG
#
# #####################################################################################
# Hall Big - Main power turned off
# ##################################
- alias: hall_big_main_power_turned_off
  id: hall_big_main_power_turned_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x158d000230fc52_switch
      to: 'off'
      from: 'on'
  # condition:
  #   - condition: state
  #     entity_id: sensor.zigbee2mqtt_bridge_state
  #     state: 'online'
  action:
    - service: notify.telegram
      data:
        message: "\U0001f50c Внимание! Главная розетка отключена! Запущен UPS (1200)"

# ##################################
# Hall Big - Main plug pulled out
# ##################################
- alias: hall_big_main_plug_pulled_out
  id: hall_big_main_plug_pulled_out
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.fridge_hb
      below: 10
  action:
    - service: notify.telegram
      data:
        message: "\U0001f50c Внимание! Нагрузка в главной розетке упала! Проверь кабель!"

# ##################################
# Hall Big - Main power - over-power
# ##################################
- alias: hall_big_main_power_overpower
  id: hall_big_main_power_overpower
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.fridge_hb
      above: 1700 
  action:
    - service: notify.telegram
      data:
        message: "\U0001f50c Внимание! Перегрузка главной розетки! Отключите лишние потребители!"

# ##################################
# Hall Big - UPS - OB
# ##################################
- alias: hall_big_ups_ob
  id: hall_big_ups_ob
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.ippon_1200_status_data
      to: 'OB'
  action:
    - service: notify.telegram
      data:
        message: "\U0001f50b Внимание! Запущен UPS (1200)!"
    - service: notify.mobile_app_iphone_12_dtsymbal
      data:
        title: "Внимание!"
        message: "Запущен UPS (1200)"

# ##################################
# Hall Big - UPS - LB
# ##################################
- alias: hall_big_ups_lb
  id: hall_big_ups_lb
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.ippon_1200_status_data
      to: 'LB'
  action:
    - service: notify.telegram
      data:
        message: "\U0001f6a8 Внимание! Заряд батареи (1200) критический! Завершение работы!"
    - service: notify.mobile_app_iphone_12_dtsymbal
      data:
        title: "Внимание!"
        message: "UPS полностью разряжен! Завершаем работу!"
        data:
          push:
            sound:
              name: "default"
              critical: 1
              volume: 1.0        
#    - service: hassio.host_shutdown

# ##################################
# Hall Big - UPS - OL
# ##################################
- alias: hall_big_ups_ol
  id: hall_big_ups_ol
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.ippon_1200_status_data
      to: 'OL'
  condition:
    - condition: template
      value_template: "{{ trigger.from_state.state not in ['unknown','unavailable','none'] }}"
  action:
    - service: notify.telegram
      data:
        message: "\U0001f50b Питание восстановлено! Начинаем заряд батареи (1200)!"

# ##################################
# Hall Big - UPS - Unknown
# ##################################
- alias: hall_big_ups_unknown
  id: hall_big_ups_unknown
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.ippon_1200_status_data
      to: 
        - unknown
        - unavailable
      for:
        minutes: 1
  condition:
    - condition: template
      value_template: "{{ trigger.from_state.state not in ['unknown','unavailable','none'] }}"
  action:
    - service: notify.telegram
      data:
        message: "\U0001f6a8 Внимание! Связь с UPS(1200) потеряна!"
    # - service: input_boolean.turn_on
    #   data:
    #     entity_id: input_boolean.ippon_1200_announce
    #- service: notify.mobile_app_iphone_12_dtsymbal
    #  data:
    #    title: "Внимание!"
    #    message: "Связь с UPS потеряна!"

# ##################################
# Hall Big - Main power turned on
# ##################################
- alias: hall_big_main_power_turned_on
  id: hall_big_main_power_turned_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x158d000230fc52_switch
      to: 'on'
      from: 'off'
  # condition:
  #   - condition: state
  #     entity_id: sensor.zigbee2mqtt_bridge_state
  #     state: 'online'
  action:
    - service: notify.telegram
      data:
        message: "\U0001f50c Электроснабжение восстановлено! Начинаем зарядку UPS(1200)!"
        
# ##################################
# Hall Big - UPS - State
# ##################################
# - alias: hall_big_ups_state
#   id: hall_big_ups_state
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: sensor.ippon_1200_status_data
#   action:
#     - service: notify.telegram
#       data:
#         message: "\U0001f50b UPS(1200): {{trigger.from_state.state}} -> {{trigger.to_state.state}} !"