# #####################################################################################
#
# HALL BIG
#
# #####################################################################################
# Hall Big - Sasha Button - Weather fcst - long
# ##################################
- alias: hall_big_weather_fcst
#  id: hall_big_weather_fcst
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x158d0002fa99a8_action
      to: 'hold'
  action:
    - service: script.weather_tts
      data:
        entity_id: media_player.{{states('input_select.main_audio_out')|lower}}
        volume_level: '{{states("input_number.main_volume")|float}}'