# #####################################################################################
#
# HALL BIG
#
# #####################################################################################
# Hall Big - Sasha Button - Weather fcst - long
# ##################################
- alias: hall_big_weather_fcst
  initial_state: true
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.click
    #   event_data:
    #     entity_id: binary_sensor.switch_158d0002fa99a8
    #     click_type: long_click_press
    - platform: state
      entity_id: sensor.0x158d0002fa99a8_action
      to: 'hold'
  action:
    - service: script.weather_tts
      data_template:
        entity_id: media_player.{{states('input_select.main_audio_out')|lower}}
        volume_level: '{{states("input_number.main_volume")|float}}'