# ##################################
# Security - Turn  On
# ##################################
- alias: security_turn_on
  id: security_turn_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.family_home
      to: "off"
  condition:
    - condition: state
      entity_id: input_boolean.security_mode
      state: "off"
  action:
    - service: notify.telegram
      data:
        message: "\U0001F3e2 Никого нет дома, выключаем освещение!"
    - service: script.turn_on
      entity_id: script.away_mode_on
    - service: notify.telegram
      data:
        message: "\U0001f514 Освещение выключено!"
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.security_mode

# ##################################
# Security - Sensors State change
# ##################################
- alias: security_sensors_state_change
  #id: security_sensors_state_change
  initial_state: true
  mode: queued
  max: 25
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.0x158d00027129ae_contact
        - binary_sensor.0x158d0001ef2ffc_contact
        - binary_sensor.0x158d0002a14c5e_contact
        - binary_sensor.0x158d0002529b9c_contact
        - binary_sensor.0x158d00025315e9_contact
        - binary_sensor.0x158d0001e5d6be_contact
        - binary_sensor.0x158d0002531749_contact
        - binary_sensor.0x158d00025371f6_contact
        - binary_sensor.0x158d000200ad58_contact
        - binary_sensor.0x158d00022ccffe_contact
        - binary_sensor.0x158d00025370d1_contact
    - platform: state
      entity_id:
        - binary_sensor.0x158d0001ae9f61_motion
        - binary_sensor.0x158d0001aea602_motion
        - binary_sensor.0x158d0003f27ce2_motion
        - binary_sensor.0x158d0001e05856_motion
        - binary_sensor.0x158d0001e53cda_motion
        - binary_sensor.0x158d0001e54280_motion
        - binary_sensor.0x158d000224f89f_motion
        - binary_sensor.0x158d000236bb94_motion
        - binary_sensor.0x158d000236bc6d_motion
        - binary_sensor.0x158d0002b4729d_motion
        - binary_sensor.0x158d0002b482e9_motion
        - binary_sensor.0x158d0002b48381_motion
        - binary_sensor.0x158d0003140824_motion
        - binary_sensor.0x158d0001d5995e_motion
        - binary_sensor.motion_g3_flex_entrance
        #- binary_sensor.motion_g3_flex_hall
        - binary_sensor.d1mini_bed_leds_motion_dima
        - binary_sensor.d1mini_bed_leds_motion_sandra
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.security_mode
      state: "on"
    - condition: state
      entity_id: timer.security_delay
      state: "idle"
  action:
    - service: notify.telegram
      data:
        #title: "Внимание!"
        message: "\U0001f46e Сработал датчик {{trigger.to_state.attributes.friendly_name}}!"

# ##################################
# Security - Alarm delay
# ##################################
- alias: security_alarm_delay
  id: security_alarm_delay
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0001e5d6be_contact
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.security_mode
      state: "on"
  action:
    - service: timer.cancel
      entity_id: timer.security_delay
    - service: timer.start
      entity_id: timer.security_delay

# ##################################
# Security - Turn Off
# ##################################
- alias: security_turn_off
  id: security_turn_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.family_home
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.security_mode
      state: "on"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.security_mode
    - service: script.turn_on
      entity_id: script.away_mode_off

# ##################################
# Security - Notification
# ##################################
- alias: security_notification
  id: security_notification
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.security_mode
  action:
    - service: notify.telegram
      data:
        message: "\U0001f46e Режим охраны {% if states('input_boolean.security_mode') == 'off' %}выключен!{% else %}включен!{% endif %}"

# # ##################################
# # Security - Security system PWR status
# # ##################################
# - alias: security_system_pwr
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.d1_security_power
#   action:
#     - service: notify.telegram
#       data:
#         message: "\U0001f693 Охранная система: питание {% if is_state('binary_sensor.d1_security_power','on') %}включено!{% else %}выключено!{% endif %}"

# # ##################################
# # Security - Security system armed
# # ##################################
# - alias: security_system_armed
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.d1_security_armed
#   action:
#     - service: notify.telegram
#       data:
#         message: "\U0001f693 Охранная система {% if is_state('binary_sensor.d1_security_armed','on') %}включена!{% else %}выключена!{% endif %}"

# # ##################################
# # Security - Security system alarm
# # ##################################
# - alias: security_system_alarm
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.d1_security_alarm
#   action:
#     - service: notify.telegram
#       data:
#         message: "\U0001f693 Охранная система: Тревога {% if is_state('binary_sensor.d1_security_alarm','on') %}включена!{% else %}выключена!{% endif %}"

# ##################################
# Security- Main door vibration
# ##################################
- alias: security_main_door_vibration
  id: security_main_door_vibration
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x158d0002b5fbc1_action
      to: "vibration"
  condition:
    - condition: state
      entity_id: input_boolean.security_mode
      state: "on"
  action:
    - service: notify.telegram
      data:
        message: "\U0001F6AA Внимание! Главная дверь - Вибрация!"

# ##################################
# Security - Sensors State change over night
# ##################################
- alias: security_sensors_state_change_night
  #id: security_sensors_state_change_night
  initial_state: true
  mode: queued
  max: 25
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.0x158d00025371f6_contact
        - binary_sensor.0x158d000200ad58_contact
        - binary_sensor.0x158d00022ccffe_contact
        - binary_sensor.0x158d00025370d1_contact
        - binary_sensor.0x158d0001e5d6be_contact
        - binary_sensor.0x158d0002531749_contact
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.tod_day
      state: "off"
    - condition: state
      entity_id: input_boolean.security_mode
      state: "off"
  action:
    - service: notify.telegram
      data:
        message: >-
          {{"\U0001f46e"}}
          {%-if trigger.to_state.attributes.device_class=='window' and trigger.to_state.state=='on'%}Открыто окно {{trigger.to_state.attributes.friendly_name}}
          {%-elif trigger.to_state.attributes.device_class=='window' and trigger.to_state.state=='off'%}Окно закрыто {{trigger.to_state.attributes.friendly_name}}
          {%-elif trigger.to_state.attributes.device_class=='door' and trigger.to_state.state=='on'%}Дверь открыта {{trigger.to_state.attributes.friendly_name}}
          {%-elif trigger.to_state.attributes.device_class=='door' and trigger.to_state.state=='off'%}Дверь закрыта {{trigger.to_state.attributes.friendly_name}}
          {%-else%}NA{%endif%}
