# ##################################
# System - Hass.io GDrive time
# ##################################
- alias: snapshot_daily_gdrive_time
  id: snapshot_daily_gdrive_time
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.gdrive_last_backup
  condition:
    - condition: template
      value_template: "{{states('sensor.ha_uptime')|float > 5}}"
  action:
    - service: notify.telegram
      data: 
        message: "\U00002705 GDrive бэкап сделан {{states('sensor.gdrive_last_backup')}}"

# ##################################
# System - Hass.io GDrive time
# ##################################
- alias: snapshot_daily_gdrive_status
  id: snapshot_daily_gdrive_status
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.gdrive_backup_state
  condition:
    - condition: template
      value_template: "{{states('sensor.ha_uptime')|float > 5}}"
  action:
    - service: notify.telegram
      data: 
        message: "\U00002705 GDrive бэкап статус {{trigger.from_state.state}} -> {{trigger.to_state.state}}"

# ##################################
# System - Hass.io GDrive Stale
# ##################################
- alias: snapshot_daily_gdrive_stale
  id: snapshot_daily_gdrive_stale
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.backups_stale
      to: 'on'
  action:
    - service: notify.telegram
      data: 
        message: "\U0000274C GDrive снапшот залип!"