# #####################################################################################
#
# Water Counting
#
# #####################################################################################
# Cold Water - Increase
# ##################################
- alias: system_water_cold_water_increase_counter
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d000232de79_contact
      from: 'on'
      to: 'off'
      for:
        seconds: 5
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.cold_water_meter
        value: "{{ (states('input_number.cold_water_meter')|float + 0.01 ) | round(2) }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.cold_water_meter_month
        value: "{{ (states('input_number.cold_water_meter_month')|float + 0.01 ) | round(2) }}"

    - service: mqtt.publish
      data_template:
        topic: "utility/main/cold_water_meter"
        payload: "{{states('sensor.cold_water_meter')|float}}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "utility/main/cold_water_meter_month"
        payload: "{{states('sensor.cold_water_meter_month')|float}}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "utility/main/cold_water_meter_input"
        payload: "{{states('input_number.cold_water_meter')|float}}"
        retain: true
        

# ##################################
# Hot Water - Increase
# ##################################
- alias: system_water_hot_water_increase_counter
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d000236fcd5_contact
      from: 'on'
      to: 'off'
      for:
        seconds: 5
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.hot_water_meter
        value: "{{ (states('input_number.hot_water_meter')|float + 0.01 ) | round(2) }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.hot_water_meter_month
        value: "{{ (states('input_number.hot_water_meter_month')|float + 0.01 ) | round(2) }}"

    - service: mqtt.publish
      data_template:
        topic: "utility/main/hot_water_meter"
        payload: "{{states('sensor.hot_water_meter')|float}}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "utility/main/hot_water_meter_month"
        payload: "{{states('sensor.hot_water_meter_month')|float}}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "utility/main/hot_water_meter_input"
        payload: "{{states('input_number.hot_water_meter')|float}}"
        retain: true

# ##################################
# System - Power Meter Daily
# ##################################
- alias: system_power_meter_daily
  initial_state: 'true'
  trigger:
    - platform: time
      at: '00:00:02'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.power_meter_t1
        value: "{{ ((states('input_number.power_meter_t1')) | float + state_attr('sensor.energy_daily_day','last_period')|float/1 )|round(2) }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.power_meter_t2
        value: "{{ ((states('input_number.power_meter_t2')) | float + state_attr('sensor.energy_daily_night','last_period')|float/1 )|round(2) }}"
    - service: mqtt.publish 
      data:
        topic: "utility/main/energy/day"
        payload: "{{ states('input_number.power_meter_t1') }}"
        retain: true
    - service: mqtt.publish 
      data:
        topic: "utility/main/energy/night"
        payload: "{{ states('input_number.power_meter_t2') }}"
        retain: true
    - service: notify.telegram
      data_template:
        message: "\U0001f50c Данные счетчика электричества обновлены!"

# ##################################
# System - Water\Power - Notification
# ##################################
- alias: system_new_month_notification
  initial_state: 'true'
  trigger:
    - platform: time
      at: '00:00:10'
  condition:
    - condition: template
      value_template: "{{ strptime(states('sensor.date'), '%Y-%m-%d').day|int == 21 }}"
  action:
    - service: mqtt.publish
      data_template:
        topic: "utility/main/{{now().year}}/{{now().month}}/hot_water_meter"
        payload: "{{states('sensor.hot_water_meter')|float}}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "utility/main/{{now().year}}/{{now().month}}/cold_water_meter"
        payload: "{{states('sensor.cold_water_meter')|float}}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "utility/main/{{now().year}}/{{now().month}}/power_meter_t1"
        payload: "{{((states('input_number.power_meter_t1'))|float)}}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "utility/main/{{now().year}}/{{now().month}}/power_meter_t2"
        payload: "{{((states('input_number.power_meter_t2'))|float)}}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "utility/main/{{now().year}}/{{now().month}}/timestamp"
        payload: "{{as_timestamp(now()) | timestamp_custom('%d-%m-%Y %H:%M:%S')}}"
        retain: true    

    - service: notify.telegram
      data_template: 
        message: >
            {{ "\U0001f4a6" }}
            Показания счетчиков:
            ХВС: {{ states('sensor.cold_water_meter')|float }}м3
            ГВС: {{ states('sensor.hot_water_meter')|float }}м3

            За месяц:
            ХВС: {{ states('sensor.cold_water_meter')|float }}м3
            ГВС: {{ states('sensor.hot_water_meter')|float }}м3
            Стоимость: {{ ((states('sensor.water_cost'))|float)}}руб.

    - service: notify.telegram
      data_template: 
        message: >
            {{ "\U0001f50c" }}
            Показания счетчика:
            Т1: {{ ((states('input_number.power_meter_t1_value'))|float)}} кВт*ч
            Т2: {{ ((states('input_number.power_meter_t2_value'))|float)}} кВт*ч

            За месяц:
            Т1: {{ ((states('sensor.energy_monthly_day')|float))|round(0)}} кВт*ч
            Т2: {{ ((states('sensor.energy_monthly_night')|float))|round(0)}} кВт*ч
            Стоимость: {{ ((states('sensor.power_cost'))|float) }} руб.

    - service: input_number.set_value
      data_template:
        entity_id: input_number.power_meter_last_month_t1
        value: "{{ state_attr('sensor.energy_monthly_day','last_period')|float}}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.power_meter_last_month_t2
        value: "{{ state_attr('sensor.energy_monthly_night','last_period')|float}}"

    - service: input_number.set_value
      data_template:
        entity_id: input_number.hot_water_meter_last_month
        value: "{{ states('input_number.hot_water_meter')|float }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.cold_water_meter_last_month
        value: "{{ states('input_number.cold_water_meter')|float }}"

    - service: input_number.set_value
      data_template:
        entity_id:
          - input_number.hot_water_meter_month
          - input_number.cold_water_meter_month
        value: 0

# #####################################################################################
#
# Power Counting
#
# #####################################################################################
# System - Power - 30sec update
# ##################################
# - alias: system_power_update_30s
#   initial_state: 'true'
#   trigger:
#     - platform: time_pattern
#       seconds: '/30'
#   action:
#     - service: >
#         {% if is_state('binary_sensor.tariff_t1','on') %}
#             script.power_t1
#         {% else %}
#             script.power_t2
#         {% endif %}
#     - service: >
#         {% if is_state('binary_sensor.tariff_t1','on') %}
#             script.power_m_t1
#         {% else %}
#             script.power_m_t2
#         {% endif %}

# ##################################
# System - Power - High current
# ##################################
- alias: system_power_15A_current
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id: sensor.esp8266_pzem_hb_current
      above: 15
      below: 20
  condition:
    - condition: template
      value_template: "{{ (as_timestamp(now())|int - as_timestamp(state_attr('automation.system_power_15A_current','last_triggered'))|int) > 10*60 }}"
  action:
    - service: notify.telegram
      data:
        message: "\U0001f6a8 Внимание! Общий ток более 15А!"
    # - service: notify.mobile_app_iphone_8_dtsymbal
    #   data:
    #     title: "Внимание!"
    #     message: "Внимание! Общий ток более 15А"
  
# ##################################
# System - Power - High current
# ##################################
- alias: system_power_20A_current
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id: sensor.esp8266_pzem_hb_current
      above: 20
      below: 30
  condition:
    - condition: template
      value_template: "{{ (as_timestamp(now())|int - as_timestamp(state_attr('automation.system_power_20A_current','last_triggered'))|int) > 10*60 }}"      
  action:
    - service: notify.telegram
      data:
        message: "\U0001f6a8 Внимание! Общий ток более 20А!"
    # - service: notify.mobile_app_iphone_8_dtsymbal
    #   data:
    #     title: "Внимание!"
    #     message: "Внимание! Общий ток более 20А"
 
# ##################################
# System - Power - Ultra High current
# ##################################
- alias: system_power_30A_current
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id: sensor.esp8266_pzem_hb_current
      above: 30
      below: 40
  condition:
    - condition: template
      value_template: "{{ (as_timestamp(now())|int - as_timestamp(state_attr('automation.system_power_30A_current','last_triggered'))|int) > 10*60 }}"      
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f6a8 Внимание! Общий ток более 30А!"
    - service: notify.mobile_app_iphone_8_dtsymbal
      data:
        title: "Внимание!"
        message: "Внимание! Общий ток более 30А"
        

# ##################################
# System - Utility meter tariff change
# ##################################
- alias: system_power_tariff_change
  initial_state: 'true'
  trigger:
    - platform: homeassistant
      event: start
    - platform: time
      at: '07:00:00'
    - platform: time
      at: '23:00:00'
  action:
    - service: utility_meter.select_tariff
      data_template:
        entity_id:
          - utility_meter.energy_daily
          - utility_meter.energy_led_monthly
          - utility_meter.energy_monthly
          - utility_meter.energy_xiaomi_monthly
          - utility_meter.plug_fridge_hb_monthly
          - utility_meter.plug_server_hb_monthly
          - utility_meter.plug_utils_hs_monthly
          - utility_meter.plug_wadrobe_v_monthly
          - utility_meter.pow_r2_1_washer_b_monthly
          - utility_meter.socket_entrance_v_monthly
          - utility_meter.socket_fridge_hb_monthly
          - utility_meter.socket_main_hs_monthly
          - utility_meter.socket_oven_k_monthly
          - utility_meter.socket_pc_k_monthly
          - utility_meter.socket_pc_mb_monthly
          - utility_meter.socket_pc_s_monthly
          - utility_meter.socket_tv_k_monthly
          - utility_meter.socket_tv_v_monthly
          - utility_meter.socket_wadrobe_s_monthly
        tariff: "{%- if is_state('binary_sensor.tariff_t1','on') -%}day{%- else -%}night{%- endif -%}"
        
# ##################################
# System - Utility meter tariff change tripple
# ##################################
- alias: system_power_tariff_change_tripple
  initial_state: 'true'
  trigger:
    - platform: homeassistant
      event: start
    - platform: time
      at: '07:00:00'
    - platform: time
      at: '10:00:00'
    - platform: time
      at: '17:00:00'
    - platform: time
      at: '21:00:00'
    - platform: time
      at: '23:00:00'
  action:
    - service: utility_meter.select_tariff
      data_template:
        entity_id: utility_meter.energy_daily_tripple
        tariff: "{%- if is_state('binary_sensor.tariff_tripple_t1','on') -%}tripple_t1{%- elif is_state('binary_sensor.tariff_tripple_t2','on') -%}tripple_t2{%- else -%}tripple_t3{%- endif -%}"