# #####################################################################################
#
# HALL SMALL  - Lights
#
# #####################################################################################
# Hall Small - Auto Light On
# ##################################
- alias: hall_small_auto_night_light
  initial_state: 'true'
  mode: restart
  # max: 5
  # max_exceeded: silent
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0001ae9f61_motion
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.0x158d0002b43ad4_motion
      from: 'off'
      to: 'on'
  condition:
    # - condition: state
    #   entity_id: binary_sensor.tod_day
    #   state: 'off'
    - condition: state
      entity_id: light.round_led_hs
      state: 'off'
    - condition: state
      entity_id: light.btf_pixel_strip_top
      state: 'off'
    - condition: state
      entity_id: light.round_led_k
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.0x4cf8cdf3c77271d_illuminance
      below: 200
  action:
    - service: light.turn_on
      entity_id: light.btf_pixel_strip_top
      data:
        brightness_pct: 45
        rgb_color: [255, 180, 107]
    # - delay: '00:00:30'
    # - service: light.turn_off
    #   entity_id: light.btf_pixel_strip_top
    #   data:
    #     transition: 5

# ##################################
# Hall Small-  Main Lamp (Xiaomi Round LED) - On
# ##################################
- alias: hall_small_main_lamp_on
  initial_state: 'true'
  mode: restart
  trigger:
    - platform: state
      entity_id: sensor.0x4cf8cdf3c7a9a48_action
      to: 'button_1_single'
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: light.round_led_hs
              state: 'on'
          sequence:
            - service: light.turn_off
              entity_id: light.round_led_hs
        - conditions:
            - condition: state
              entity_id: light.round_led_hs
              state: 'off'
          sequence:
            - service: light.turn_on
              entity_id: light.round_led_hs
              data_template:
                brightness_pct: 25
                kelvin: 5000

# ##################################
# Hall Small-  Main Lamp (Xiaomi Round LED) - Double
# ##################################
- alias: hall_small_main_lamp_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x4cf8cdf3c7a9a48_action
      to: 'button_1_double'
  action:
    - service: light.turn_on
      entity_id: light.round_led_hs
      data_template:
        brightness_pct: 90
        kelvin: 5000
        
# ##################################
# Hall Small - Main Lamp Reset 
# ##################################
- alias: hall_small_main_lamp_reset
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: state
      entity_id: light.round_led_hs
      state: 'unavailable'
      for:
        minutes: 2
  action:
    - service: script.turn_on
      entity_id: script.round_led_hs_restart
      
# ##################################
# Hall small - LED STrip Timer start
# ################################## 
- alias: hall_small_led_strip_timer_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: light.btf_pixel_strip_top
      to: 'on'
      from: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.night_led_strip_hs
    - service: timer.start
      entity_id: timer.night_led_strip_hs

# ##################################
# Hall small - Auto LED Strips off
# ##################################
- alias: hall_small_led_strip_auto_led_off
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.night_led_strip_hs
  action:
    - service: light.turn_off
      entity_id: light.btf_pixel_strip_top
      data:
        transition: 5
        
# ##################################
# Hall small - LED Strip Timer restart with movement
# ################################## 
- alias: hall_small_led_strip_timer_restart
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0001ae9f61_motion
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.0x158d0002b43ad4_motion
      from: 'off'
      to: 'on'
  condition:
    # - condition: state
    #   entity_id: binary_sensor.tod_day
    #   state: 'off'
    - condition: template
      value_template: "{{(as_timestamp(now())-as_timestamp(states.automation.hall_small_led_strip_timer_restart.attributes.last_triggered)|int) > 5 }}"
    - condition: state
      entity_id: light.btf_pixel_strip_top
      state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.night_led_strip_hs
    - service: timer.start
      entity_id: timer.night_led_strip_hs