# #####################################################################################
#
# SASHA - breather
#
# #####################################################################################
# Sasha- breather On
# ##################################
- alias: sasha_breather_auto
  id: sasha_breather_auto
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: "/5"
  condition:
    - condition: state
      entity_id: switch.breather_auto_s
      state: "on"
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: binary_sensor.family_home
              state: "on"
            - condition: numeric_state
              entity_id: sensor.z19_co2_s
              above: 1000
            - condition: state
              entity_id: binary_sensor.breather_s
              state: "off"
            # - condition: state
            #   entity_id: binary_sensor.0x158d00025370d1_contact
            #   state: "off"
        - condition: and
          conditions:
            - condition: numeric_state
              entity_id: sensor.z19_co2_s
              below: 600
            - condition: state
              entity_id: binary_sensor.breather_s
              state: "on"
  action:
    - service: button.press
      entity_id: button.digma_ir_s_breather_pwr