# #####################################################################################
#
# SASHA - Cube
#
# #####################################################################################
# Sasha - Cube play 
# ##################################
- alias: sasha_play_night
  initial_state: false
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000116b03f
        action_type: shake_air
  condition: 
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.home_mini_s
          state: 'off'
        - condition: state
          entity_id: media_player.home_mini_s
          state: 'idle'
    - condition: time
      after: '07:00'
      before: '06:00'  
  action:
    - service:  media_player.turn_on
      entity_id: media_player.home_mini_s
    - service:  media_player.volume_set
      entity_id: media_player.home_mini_s
      data:
        volume_level: 0.1
    - service: media_player.play_media
      entity_id: media_player.home_mini_s
      data:
        media_content_id: "http://192.168.1.14:8123/local/mp3/goodnight.mp3"
        media_content_type: "audio/mp3"

# ##################################
# Sasha - Cube stop
# ##################################
- alias: sasha_stop_night
  initial_state: false
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000116b03f
        action_type: shake_air
  condition: 
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.home_mini_s
          state: 'on'
        - condition: state
          entity_id: media_player.home_mini_s
          state: 'playing'
    - condition: time
      after: '07:00'
      before: '06:00'  
  action:
    - service:  media_player.turn_off
      entity_id: media_player.home_mini_s
#    - service:  media_player.volume_set
#      entity_id: media_player.home_mini_s
#      data:
#        volume_level: 1
#    - service: media_player.play_media
#      entity_id: media_player.home_mini_s
#      data:
#        media_content_id: "http://192.168.1.14:8123/local/goodnight.mp3"
#        media_content_type: "audio/mp3"

#ube	cube	MFKZQ01LM	off (always)	xiaomi_aqara.cube_action	action_type, action_value (rotate)	flip90, flip180, move, tap_twice, shake_air, swing, alert, free_fall, rotate (degrees at action_value)