# #####################################################################################
#
# SASHA - Humidifier
#
# #####################################################################################
# Sasha - Humidifier 2 low water notify to Telegram
# ##################################
- alias: sasha_humidifier_water_low_water_cond
  id: sasha_humidifier_water_low_water_cond
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.humidifier_water_level
      below: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.tod_day
        state: 'on'
      - condition: state
        entity_id: person.dima
        state: 'home'
      - condition: template
        value_template: "{{(as_timestamp(now())-as_timestamp(state_attr('automation.sasha_humidifier_water_low_water_cond','last_triggered'))|int) > 30*60 }}"
  action:
    service: notify.telegram
    data_template:
      message: "\U0001f4a7 Увлажнитель - осталось менее 10% воды!"
      
# ##################################
# Sasha - Humidifier2  Reset
# ##################################
- alias: sasha_humidifier_reset
  id: sasha_humidifier_reset
  initial_state: true
  trigger:
    - platform: state
      entity_id: fan.humidifier2
      to: 'unavailable'
      for:
        minutes: 5
  action:
    - service: script.turn_on
      entity_id: script.humidifier2_restart
