# #####################################################################################
#
# SASHA - Humidifier
#
# #####################################################################################
# Sasha - Humidifier 2 low water notify to Telegram
# ##################################
- alias: sasha_humidifier_water_low_water_cond
  #id:sasha_humidifier_water_low_water_cond
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.humidifier2_water_level
      below: 10
      for:
        minutes: 3
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.tod_day
        state: 'on'
      - condition: state
        entity_id: person.dima
        state: 'home'
      - condition: template
        value_template: "{{(as_timestamp(now())-as_timestamp(state_attr('automation.sasha_humidifier_water_low_water_cond', 'last_triggered'))|int(0)) > 30*60 }}"
  action:
    service: notify.telegram
    data:
      message: "\U0001f4a7 Увлажнитель - осталось менее 10% воды!"
      
# ##################################
# Sasha - Humidifier2  Restart
# ##################################
- alias: sasha_humidifier_restart
  #id:sasha_humidifier_restart
  initial_state: true
  trigger:
    - platform: state
      entity_id: humidifier.humidifier2
      to: 'unavailable'
      for:
        minutes: 5
  action:
    - service: script.turn_on
      entity_id: script.humidifier2_restart
      
# ##################################
# Sasha - Humidifier2  Set Target Humidity
# ##################################
- alias: sasha_humidifier_set_target_humidity
  #id:sasha_humidifier_set_target_humidity
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_select.humidifier2_target_humidity
  action:
    - service: humidifier.set_humidity
      data:
        entity_id: humidifier.humidifier2
        humidity: "{{ states('input_select.humidifier2_target_humidity') }}"


# # ##################################
# # Sasha - Humidifier2  Get Target Humidity
# # ##################################
# - alias: sasha_humidifier_get_target_humidity
# #- id: sasha_humidifier_get_target_humidity  
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: humidifier.humidifier2
#       attribute: target_humidity
#   condition:
#     - condition: template
#       value_template: >
#         {% set ignore = ['unknown', 'unavailable', 'none'] %}
#         {{ trigger.from_state.state not in ignore and
#           trigger.to_state.state not in ignore and
#           trigger.to_state.state != trigger.from_state.state }}
#   action:
#     - service: input_select.select_option
#       entity_id: input_select.humidifier2_target_humidity
#       data:
#         option: >
#           {{ state_attr('humidifier.humidifier2','target_humidity') }}