# #####################################################################################
#
# SASHA - Lights
#
# #####################################################################################
# Sasha Table Lamp (Philips E27)
# ##################################
- alias: sasha_table_lamp
#  id: sasha_table_lamp
  initial_state: true
  mode: queued
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001f3627d_action
      to:
        - single
        - double
        - hold      
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: sensor.0x158d0001f3627d_action
              state: 'single'
          sequence:
            - service: light.toggle
              entity_id: light.led_white_s
        - conditions:
            - condition: state
              entity_id: sensor.0x158d0001f3627d_action
              state: 'double'
          sequence:
            - service: light.turn_on
              entity_id: light.led_white_s
              data_template:
                brightness_pct: 100
                kelvin: 5000
        - conditions:
            - condition: state
              entity_id: sensor.0x158d0001f3627d_action
              state: 'hold'
          sequence:
            - service: light.turn_on
              entity_id: light.led_white_s
              data_template:
                brightness_pct: 5
                kelvin: 3000

# ##################################
# Sasha - Main Lamp (Xiaomi Round LED)
# ##################################
- alias: sasha_main_lamp_left_button
#  id: sasha_main_lamp_left_button
  initial_state: true
  mode: queued
  trigger:
    - platform: state
      entity_id: sensor.0x158d00026eb820_action
      to: 'button_1_single'
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: light.square_led_s
              state: 'on'
          sequence:
            - service: light.turn_off
              entity_id: light.square_led_s
        - conditions:
            - condition: state
              entity_id: light.square_led_s
              state: 'off'
          sequence:
            - service: light.turn_on
              entity_id: light.square_led_s
              data_template:
                brightness_pct: 80
                kelvin: 5000

# ##################################
# Sasha - Main Lamp (Xiaomi Round LED)
# ##################################
- alias: sasha_main_lamp_right_button
#  id: sasha_main_lamp_right_button
  initial_state: true
  mode: queued
  trigger:
    - platform: state
      entity_id: sensor.0x158d00026eb820_action
      to: 'button_2_single'
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: light.square_led_s
              state: 'on'
          sequence:
            - service: light.turn_off
              entity_id: light.square_led_s
        - conditions:
            - condition: state
              entity_id: light.square_led_s
              state: 'off'
          sequence:
            - service: light.turn_on
              entity_id: light.square_led_s
              data_template:
                brightness_pct: 5
                kelvin: 3000

# ##################################
# Sasha - Table Lamp Off (scene4) when main turned on
# ################################## 
- alias: sasha_table_lamp_off_night_mode_main_on
#  id: sasha_table_lamp_off_night_mode_main_on
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: "/3"
  condition:
    - condition: template
      value_template: "{{state_attr('light.led_white_s','brightness')|int < 10}}"
    - condition: state
      entity_id: light.square_led_s
      state: 'on'
    - condition: state
      entity_id: light.led_white_s
      state: 'on'
    - condition: state
      entity_id: binary_sensor.tod_day
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.led_white_s

# ##################################
# Sasha - Auto Night Light
# ##################################
# - alias: sasha_auto_nightlight_on
#   initial_state: false
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.0x158d000224f89f_motion, binary_sensor.0x158d000224f89f_motion
#       #from: 'off'
#       to: 'on'
#   condition:
#     condition: and
#     conditions:
#       - condition: state
#         entity_id: binary_sensor.tod_day
#         state: 'off'
#       - condition: state
#         entity_id: person.sasha
#         state: 'home'
#   action:
#     - service: light.turn_on
#       entity_id: light.led_white_s
#       data_template:
#         brightness_pct: 5
#         kelvin: 3000      

# ##################################
# Sasha - Auto Night Light Off 30m without movements
# ##################################
- alias: sasha_night_auto_off_30m
#  id: sasha_night_auto_off_30m
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_s
      from: 'on'
      to: 'off'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: binary_sensor.tod_day
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.led_white_s
      data:
        transition: 5

# ##################################
# Sasha - Round LED Reset 
# ##################################
- alias: sasha_round_led_reset
#  id: sasha_round_led_reset
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: state
      entity_id: light.square_led_s
      state: 'unavailable'
      for:
        minutes: 2
  action:
    - service: script.turn_on
      entity_id: script.square_led_s_restart

# ##################################
# Sasha - Turn Lamp Switch On if Off
# ##################################
- alias: sasha_main_lamp_switch_on_if_off
#  id: sasha_main_lamp_switch_on_if_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x158d00026eb820_action
      to: 'button_1_single'
    - platform: state
      entity_id: sensor.0x158d00026eb820_action
      to: 'button_2_single'
  condition:
    condition: state
    entity_id: switch.sonoff_mini_2_relay
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.sonoff_mini_2_relay

# ##################################
# Sasha - Timer restart with movement
# ################################## 
- alias: sasha_timer_restart
#  id: sasha_timer_restart
  initial_state: true
  mode: queued
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d000224f89f_motion, binary_sensor.0x158d0003140824_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: light.square_led_s
      state: 'on'
    - condition: template
      value_template: "{{(as_timestamp(now())-as_timestamp(state_attr('automation.sasha_timer_restart','last_triggered'))|int) > 15 }}"
  action:
    - service: timer.cancel
      entity_id: timer.main_light_s
    - service: timer.start
      entity_id: timer.main_light_s

# # ##################################
# # Sasha - Timer off
# # ################################## 
# - alias: sasha_timer_off
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: light.square_led_s
#       to: 'off'
#       from: 'on'
#   action:
#     - service: timer.cancel
#       entity_id: timer.main_light_s
#    - service: automation.turn_off
#      entity_id: automation.sasha_auto_light_on
#    - delay: '00:00:10'
#    - service: automation.turn_on
#      entity_id: automation.sasha_auto_light_on
    
# ##################################
# Sasha - Timer start on light on
# ################################## 
- alias: sasha_timer_on
#  id: sasha_timer_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.square_led_s
      to: 'on'
      from: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_s
    - service: timer.start
      entity_id: timer.main_light_s

# ##################################
# Sasha - Auto Light Off
# ##################################
- alias: sasha_auto_light_off
#  id: sasha_auto_light_off
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.main_light_s
  condition:
    - condition: state
      entity_id: binary_sensor.tod_day
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.square_led_s
      data:
        transition: 5

# ##################################
# Sasha - LED Strip Control with round key
# ##################################
- alias: sasha_led_strip_control
#  id: sasha_led_strip_control
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x158d00019c8afd_action
      to: 
        - single
        - double
        - hold
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: sensor.0x158d00019c8afd_action
              state: 'single'
          sequence:
            - service: light.turn_on
              data_template:
                entity_id: light.d1mini_co2_s_led
                effect: '{{ (["Random", "Rainbow", "Color Wipe", "Scan", "Twinkle", "Random Twinkle"] | random) }}'
        - conditions:
            - condition: state
              entity_id: sensor.0x158d00019c8afd_action
              state: 'double'
          sequence:
            - service: light.turn_on
              data_template:
                entity_id: light.d1mini_co2_s_led
                effect: 'Color Wipe'
        - conditions:
            - condition: state
              entity_id: sensor.0x158d00019c8afd_action
              state: 'hold'
          sequence:
            - service: light.turn_off
              entity_id: light.d1mini_co2_s_led
              data:
                transition: 5

# ##################################
# Sasha - LED Color V
# ##################################
- alias: sasha_led_color_v_reset
#  id: sasha_led_color_v_reset
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: state
      entity_id: light.led_color_v
      state: 'unavailable'
      for:
        minutes: 2
  action:
    - service: script.turn_on
      entity_id: script.led_color_v_restart