substitutions:
  board_name: d1mini_distance_sensor
  node_name: d1mini-distance-sensor
  
esphome:
  name: ${node_name}
  comment: D1 Mini Toilet Distance Sensor
  # includes:
  #   - ld2410_uart.h
  # on_boot:
  #   priority: 600
  #   # ...
  #   then:
  #     - lambda: |-
  #         auto uart_component = static_cast<LD2410 *>(ld2410);
  #         uart_component->setNumbers(maxMovingDistanceRange, maxStillDistanceRange, noneDuration);

esp8266:
  board: d1_mini
  restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid_k
  password: !secret wifi_pass
  domain: .local
  reboot_timeout: 15min
  #output_power: 17.5dB
  fast_connect: true
  #power_save_mode: none
  # manual_ip:
  #   static_ip: 192.168.1.113
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0
  #   dns1: 192.168.1.1
  #   dns2: 8.8.8.8

logger:
  baud_rate: 0
  
api:
  reboot_timeout: 0s

ota:

web_server:
  port: 80

i2c:
  sda: GPIO04
  scl: GPIO05
  scan: True

# uart:
#   id: uart1
#   tx_pin: GPIO01
#   rx_pin: GPIO03
#   baud_rate: 256000 # Change this according to your setting
#   parity: NONE
#   stop_bits: 1
  # debug:
  #   direction: BOTH
  #   dummy_receiver: false
  #   after:
  #     delimiter: [0xF8,0xF7,0xF6,0xF5]

# custom_component:
#   - lambda: |-
#       return {new LD2410(id(uart1))};
#     components:
#       - id: ld2410

binary_sensor:
  - platform: status
    name: ${board_name}_Status

  - platform: template
    name: ${board_name}_Occupancy
    device_class: occupancy
    icon: mdi:account-eye
    id: occupancy_binary
    # filters:
    #   - delayed_on_off: 10s
    lambda: |-
      if ((id(id_distance).state > 0.1) && (id(id_distance).state < 1.8)) {
        return true;
      } else {
        return false;
      }

  # - platform: custom
  #   lambda: |-
  #     auto uart_component = static_cast<LD2410 *>(ld2410);
  #     return {uart_component->hasTarget,uart_component->hasMovingTarget,uart_component->hasStillTarget,uart_component->lastCommandSuccess};
  #   binary_sensors:
  #     - name: ${board_name}_Has Target
  #     - name: ${board_name}_Has Moving Target
  #     - name: ${board_name}_Has Still Target
  #     - name: ${board_name}_Last Command Success

  - platform: gpio
    pin: GPIO14
    name: ${board_name}_Radar
    device_class: occupancy

text_sensor:
  - platform: template
    name: ${board_name}_Uptime
    lambda: |-
        int seconds = round(id(uptime_sensor).raw_state);
        int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600);
        int hours = seconds / 3600;
        seconds = seconds % 3600;
        int minutes = seconds /  60;
        seconds = seconds % 60;
        return (
          (days ? to_string(days) + "d " : "00d ") +
          (hours ? to_string(hours) + "h " : "00h ") +
          (minutes ? to_string(minutes) + "m " : "00m ") +
          (to_string(seconds) + "s")
        );
    icon: mdi:clock-start
    update_interval: 15s

  - platform: wifi_info
    ip_address:
      name: ${board_name}_IP
    ssid:
      name: ${board_name}_SSID
    bssid:
      name: ${board_name}_BSSID
    mac_address:
      name: ${board_name}_Mac
    scan_results:
      name: ${board_name}_Latest_Scan_Results

  - platform: version
    name: ${board_name}_ESPHome_Version
    hide_timestamp: true

  - platform: template
    name: ${board_name}_Occupancy_Text
    icon: mdi:account-search
    id: occupancy_text
    lambda: |-
      if ( id(id_distance).state > 0.1  && id(id_distance).state <= 0.7 ) {
        return {"Sitting"};
      } 
      if ( id(id_distance).state > 0.7  && id(id_distance).state <= 1.5 ) {
      return {"Standing"}; 
      } 
      else 
      {
      return {"NA"};
      }

sensor:
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor
    update_interval: 15s

  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s

  - platform: vl53l0x
    name: ${board_name}_Distance
    address: 0x29
    update_interval: 5s
    long_range: true
    id: id_distance
    on_value:
      then:
        - component.update: occupancy_text

  # - platform: custom
  #   internal: true
  #   lambda: |-
  #     auto uart_component = static_cast<LD2410 *>(ld2410);
  #     return {uart_component->movingTargetDistance,uart_component->movingTargetEnergy,uart_component->stillTargetDistance,uart_component->stillTargetEnergy,uart_component->detectDistance};
  #   sensors:
  #     - name: ${board_name}_Moving Target Distance
  #       unit_of_measurement: "cm"
  #       accuracy_decimals: 0
  #     - name: ${board_name}_Moving Target Energy
  #       unit_of_measurement: "%"
  #       accuracy_decimals: 0
  #     - name: ${board_name}_Still Target Distance
  #       unit_of_measurement: "cm"
  #       accuracy_decimals: 0
  #     - name: ${board_name}_Still Target Energy
  #       unit_of_measurement: "%"
  #       accuracy_decimals: 0
  #     - name: ${board_name}_Detect Distance
  #       unit_of_measurement: "cm"
  #       accuracy_decimals: 0

# number:        
#   - platform: template
#     name: ${board_name}_Max Moving Distance Range
#     id: maxMovingDistanceRange
#     min_value: 1
#     max_value: 8
#     step: 1
#     update_interval: never
#     optimistic: true
#     set_action:
#       - lambda: |-
#           auto uart_component = static_cast<LD2410 *>(ld2410);
#           uart_component->setMaxDistancesAndNoneDuration(x,id(maxStillDistanceRange).state,id(noneDuration).state);
#   - platform: template
#     name: ${board_name}_Max Still Distance Range
#     id: maxStillDistanceRange
#     min_value: 1
#     max_value: 8
#     step: 1
#     update_interval: never
#     optimistic: true
#     set_action:
#       - lambda: |-
#           auto uart_component = static_cast<LD2410 *>(ld2410);
#           uart_component->setMaxDistancesAndNoneDuration(id(maxMovingDistanceRange).state,x,id(noneDuration).state);
#   - platform: template
#     name: ${board_name}_None Duration
#     id: noneDuration
#     min_value: 0
#     max_value: 32767
#     step: 1
#     mode: box
#     update_interval: never
#     optimistic: true
#     set_action:
#       - lambda: |-
#           auto uart_component = static_cast<LD2410 *>(ld2410);
#           uart_component->setMaxDistancesAndNoneDuration(id(maxMovingDistanceRange).state,id(maxStillDistanceRange).state,x);

button:
  - platform: restart
    name: ${board_name}_Restart

  # - platform: template
  #   name: ${board_name}_Reboot LD2410
  #   on_press:
  #     lambda: 'static_cast<LD2410 *>(ld2410)->reboot();'
  # - platform: template
  #   name: ${board_name}_Turn on config mode
  #   on_press:
  #     - lambda: 'static_cast<LD2410 *>(ld2410)->setConfigMode(true);'
  # - platform: template
  #   name: ${board_name}_Turn off config mode
  #   on_press:
  #     - lambda: 'static_cast<LD2410 *>(ld2410)->setConfigMode(false);'
  # - platform: template
  #   name: ${board_name}_Get config
  #   on_press:
  #     - lambda: 'static_cast<LD2410 *>(ld2410)->queryParameters();'
  # - platform: template
  #   name: ${board_name}_Set baud rate to 256000
  #   on_press:
  #     - lambda: 'static_cast<LD2410 *>(ld2410)->setBaudrate(7);'
  # - platform: template
  #   name: ${board_name}_Set baud rate to 115200
  #   on_press:
  #     - lambda: 'static_cast<LD2410 *>(ld2410)->setBaudrate(5);'
  # - platform: template
  #   name: ${board_name}_Set baud rate to 9600
  #   on_press:
  #     - lambda: 'static_cast<LD2410 *>(ld2410)->setBaudrate(1);'

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Moscow