substitutions:
  board_name: d1mini_co2_s
 
esphome:
  name: ${board_name}
  comment: D1 Mini CO2\LED\Api Monitor\TH Node S


esp8266:
  board: d1_mini
  framework:
    version: 2.7.4
    
wifi:
  ssid: !secret wifi_ssid_s
  password: !secret wifi_pass
  domain: .local
  reboot_timeout: 15min
  #output_power: 17.5dB
  fast_connect: true
  #power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.106
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 8.8.8.8
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 5min

ota:

# web_server:
#   port: 80
  
binary_sensor:
  - platform: status
    name: ${board_name}_Status
    
uart:
  rx_pin: D1
  tx_pin: D2
  baud_rate: 9600

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO14
    num_leds: 75
    rgb_order: GRB
    name: ${board_name}_LED
    effects:
      - random:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:

text_sensor:
  - platform: template
    name: ${board_name}_Uptime
    lambda: |-
        int seconds = round(id(uptime_sensor).raw_state);
        int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600);
        int hours = seconds / 3600;
        seconds = seconds % 3600;
        int minutes = seconds /  60;
        seconds = seconds % 60;
        return (
          (days ? to_string(days) + "d " : "00d ") +
          (hours ? to_string(hours) + "h " : "00h ") +
          (minutes ? to_string(minutes) + "m " : "00m ") +
          (to_string(seconds) + "s")
        );
    icon: mdi:clock-start
    update_interval: 15s

  - platform: wifi_info
    ip_address:
      name: ${board_name}_IP
    ssid:
      name: ${board_name}_SSID
    bssid:
      name: ${board_name}_BSSID
    mac_address:
      name: ${board_name}_Mac
    scan_results:
      name: ${board_name}_Latest_Scan_Results

  - platform: version
    name: ${board_name}_ESPHome_Version
    hide_timestamp: true

sensor:
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor
    update_interval: 15s

  # - platform: mhz19
  #   co2:
  #     name: "Z19 CO2 S"
  #   temperature:
  #     name: "Z19 Temp S"
  #   update_interval: 60s
  #   id: my_mhz19_id
  #   automatic_baseline_calibration: true

  - platform: senseair
    co2:
      name: ${board_name}_CO2
    update_interval: 60s

  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s    

button:
  - platform: restart
    name: ${board_name}_Restart

# switch:
#   - platform: template
#     name: ${board_name}_MH-Z19 ABC
#     optimistic: true
#     on_turn_on:
#       mhz19.abc_enable: my_mhz19_id
#     on_turn_off:
#       mhz19.abc_disable: my_mhz19_id

#   - platform: template
#     name: ${board_name}_MH-Z19 Calibrate
#     on_turn_on:
#       mhz19.calibrate_zero: my_mhz19_id
#     turn_off_action:
#       switch.turn_off: mhz19_zero
#     id: mhz19_zero

  # - platform: template
  #   name: "Z19 ABC"
  #   optimistic: true
  #   on_turn_on:
  #     mhz19.abc_enable: my_mhz19_id
  #   on_turn_off:
  #     mhz19.abc_disable: my_mhz19_id

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Moscow