substitutions:
  board_name: d1mini_sim800
  node_name: d1mini-sim800
 
esphome:
  name: ${node_name}
  comment: D1 Mini SIM800L Node


esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  #domain: .local
  reboot_timeout: 15min
  #output_power: 17.5dB
  fast_connect: true
  #power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.184
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 8.8.8.8
    
logger:
  baud_rate: 0

api:
  reboot_timeout: 0s
  services:
    - service: send_sms
      variables:
        recipient: string
        message: string
      then:
      - sim800l.send_sms:
          recipient: !lambda 'return recipient;'
          message: !lambda 'return message;'
    - service: dial
      variables:
        recipient: string
      then:
      - sim800l.dial:
          recipient: !lambda 'return recipient;'
        
ota:

web_server:
  port: 80
  
binary_sensor:
  - platform: status
    name: ${board_name}_Status
    
  - platform: sim800l
    registered:
      name: ${board_name}_Sim800L_Registered
      
uart:
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 115200

# sim800l:
#   on_sms_received:
#     - logger.log:
#         format: "Received '%s' from %s"
#         args: [ 'message.c_str()', 'sender.c_str()' ]

sim800l:
  on_sms_received:
  - lambda: |-
      id(sms_sender).publish_state(sender);
      id(sms_message).publish_state(message);

text_sensor:
  - platform: template
    name: ${board_name}_Uptime
    lambda: |-
        int seconds = round(id(uptime_sensor).raw_state);
        int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600);
        int hours = seconds / 3600;
        seconds = seconds % 3600;
        int minutes = seconds /  60;
        seconds = seconds % 60;
        return (
          (days ? to_string(days) + "d " : "00d ") +
          (hours ? to_string(hours) + "h " : "00h ") +
          (minutes ? to_string(minutes) + "m " : "00m ") +
          (to_string(seconds) + "s")
        );
    icon: mdi:clock-start
    update_interval: 15s

  - platform: wifi_info
    ip_address:
      name: ${board_name}_IP
    ssid:
      name: ${board_name}_SSID
    bssid:
      name: ${board_name}_BSSID
    mac_address:
      name: ${board_name}_Mac
    scan_results:
      name: ${board_name}_Latest_Scan_Results

  - platform: version
    name: ${board_name}_ESPHome_Version
    hide_timestamp: true

  - platform: template
    id: sms_sender
    name: ${board_name}_Sms_Sender
  - platform: template
    id: sms_message
    name: ${board_name}_Sms_Message

sensor:
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor
    update_interval: 15s

  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s    

  - platform: sim800l
    rssi:
      name: ${board_name}_Sim800L_RSSI

button:
  - platform: restart
    name: ${board_name}_Restart

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Moscow