substitutions:
  board_name: esp32_node_mb
  node_name: esp32-node-mb
 
esphome:
  name: ${node_name}
  comment: ESP32 CO2 TPH Node MB

esp32:
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid_mb
  password: !secret wifi_pass
  domain: .local
  reboot_timeout: 15min
  #output_power: 17.5dB
  fast_connect: true
  #power_save_mode: none
  # networks:
  #   - ssid: !secret wifi_ssid
  #     password: !secret wifi_pass
  #     hidden: false
  #     bssid: !secret wifi_bssid_mb_main
  #     priority: 0
  #   - ssid: !secret wifi_ssid
  #     password: !secret wifi_pass
  #     hidden: false
  manual_ip:
    static_ip: 192.168.1.104
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 8.8.8.8

logger:
  
api:
  reboot_timeout: 0s

ota:

web_server:
  port: 80
  
binary_sensor:
  - platform: status
    name: ${board_name}_Status
    
uart:
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 9600

dallas:
  - pin: GPIO26
    update_interval: 60s
    id: dallas_node_short

  - pin: GPIO27
    update_interval: 60s
    id: dallas_node_long

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: True

text_sensor:
  - platform: template
    name: ${board_name}_Uptime
    lambda: |-
        int seconds = round(id(uptime_sensor).raw_state);
        int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600);
        int hours = seconds / 3600;
        seconds = seconds % 3600;
        int minutes = seconds /  60;
        seconds = seconds % 60;
        return (
          (days ? to_string(days) + "d " : "00d ") +
          (hours ? to_string(hours) + "h " : "00h ") +
          (minutes ? to_string(minutes) + "m " : "00m ") +
          (to_string(seconds) + "s")
        );
    icon: mdi:clock-start
    update_interval: 15s
  
  - platform: wifi_info
    ip_address:
      name: ${board_name}_IP
    ssid:
      name: ${board_name}_SSID
    bssid:
      name: ${board_name}_BSSID
    mac_address:
      name: ${board_name}_Mac
    scan_results:
      name: ${board_name}_Latest_Scan_Results

  - platform: version
    name: ${board_name}_ESPHome_Version
    hide_timestamp: true
    
sensor:
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor
    update_interval: 15s

  - platform: dallas
    address: 0x0C0120462D297E28
    dallas_id: dallas_node_long
    name: ${board_name}_Outside
    accuracy_decimals: 2
    resolution: 12
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 1
      
  - platform: dallas
    address: 0xA83C01D607703828
    dallas_id: dallas_node_short
    name: ${board_name}_Heating_Pipe
    accuracy_decimals: 2
    resolution: 12

  - platform: senseair
    co2:
      name: ${board_name}_CO2
    update_interval: 60s
    id: id_my_co2
    
  - platform: bme280
    temperature:
      name: ${board_name}_Temperature
      oversampling: 16x
      id: bme280_temperature
   
    pressure:
      name: ${board_name}_Pressure
      id: bme280_pressure
    humidity:
      name: ${board_name}_Humidity
      id: bme280_humidity
      filters:
        - offset: 5.0      
    address: 0x76
    update_interval: 30s

  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s

switch:
  - platform: template
    name: ${board_name}_ABC
    restore_state: true
    optimistic: true
    on_turn_on:
      - senseair.abc_enable: id_my_co2
    on_turn_off:
      - senseair.abc_disable: id_my_co2

button:
  - platform: restart
    name: ${board_name}_Restart

  - platform: template
    name: ${board_name}_CO2_Calibtrate
    on_press:
      - senseair.background_calibration: id_my_co2

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Moscow