substitutions:
  board_name: esp32_node_v
 
esphome:
  name: ${board_name}
  comment: ESP32 CO2 TPH Node V

esp32:
  board: lolin32

wifi:
  ssid: !secret wifi_ssid_s
  password: !secret wifi_pass
  domain: .local
  reboot_timeout: 15min
  #output_power: 17.5dB
  fast_connect: true
  #power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.105
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 8.8.8.8

logger:
  baud_rate: 0
  
api:
  reboot_timeout: 0s

ota:

web_server:
  port: 80
  
binary_sensor:
  - platform: status
    name: ${board_name}_Status
    
uart:
  rx_pin: GPIO03
  tx_pin: GPIO01
  baud_rate: 9600

dallas:
  - pin: GPIO26
    update_interval: 15s
    id: dallas_node

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: True

text_sensor:
  - platform: template
    name: ${board_name}_Uptime
    lambda: |-
        int seconds = round(id(uptime_sensor).raw_state);
        int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600);
        int hours = seconds / 3600;
        seconds = seconds % 3600;
        int minutes = seconds /  60;
        seconds = seconds % 60;
        return (
          (days ? to_string(days) + "d " : "00d ") +
          (hours ? to_string(hours) + "h " : "00h ") +
          (minutes ? to_string(minutes) + "m " : "00m ") +
          (to_string(seconds) + "s")
        );
    icon: mdi:clock-start
    update_interval: 15s
  
  - platform: wifi_info
    ip_address:
      name: ${board_name}_IP
    ssid:
      name: ${board_name}_SSID
    bssid:
      name: ${board_name}_BSSID
    mac_address:
      name: ${board_name}_Mac
    scan_results:
      name: ${board_name}_Latest_Scan_Results

  - platform: version
    name: ${board_name}_ESPHome_Version
    hide_timestamp: true

sensor:
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor
    update_interval: 15s

  - platform: dallas
    address: 0x0101143E424CAA28
    name: ${board_name}_Heating_Pipe
    accuracy_decimals: 2
    resolution: 12

  # - platform: mhz19
  #   co2:
  #     name: "Z19 CO2 V"
  #   temperature:
  #     name: "Z19 Temp V"
  #   update_interval: 60s
  #   id: my_mhz19_id
  #   automatic_baseline_calibration: false
  
  - platform: senseair
    co2:
      name: ${board_name}_CO2
    update_interval: 60s  
  
  - platform: bme280
    temperature:
      name: ${board_name}_Temperature
      oversampling: 16x
      id: bme280_temperature
    pressure:
      name: ${board_name}_Pressure
      id: bme280_pressure
    humidity:
      name: ${board_name}_Humidity
      id: bme280_humidity
    address: 0x76
    update_interval: 30s

  # - platform: bh1750
  #   name: ${board_name}_Illuminance
  #   address: 0x23
  #   #measurement_duration: 254
  #   update_interval: 15s
  #   accuracy_decimals: 0
    
  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s
    
button:
  - platform: restart
    name: ${board_name}_Restart

# switch:
#   - platform: template
#     name: ${board_name}_MH-Z19 ABC
#     optimistic: true
#     on_turn_on:
#       mhz19.abc_enable: my_mhz19_id
#     on_turn_off:
#       mhz19.abc_disable: my_mhz19_id

#   - platform: template
#     name: ${board_name}_MH-Z19 Calibrate
#     on_turn_on:
#       mhz19.calibrate_zero: my_mhz19_id
#     turn_off_action:
#       switch.turn_off: mhz19_zero
#     id: mhz19_zero

time:
  - platform: homeassistant
    id: homeassistant_time