substitutions:
  board_name: esp32_node_hs
  node_name: esp32-node-hs
 
esphome:
  name: ${node_name}
  comment: ESP32 TPH Node HS
  # platformio_options:
  #   board_build.partitions: ../../../custom_components/partitions_esp32_4mb.csv

esp32:
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid_k
  password: !secret wifi_pass
  domain: .local
  reboot_timeout: 15min
  #output_power: 10dB
  fast_connect: true
  #power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.38
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 8.8.8.8

logger:
  baud_rate: 0
  
api:
  reboot_timeout: 0s

ota:

web_server:
  port: 80
  
binary_sensor:
  - platform: status
    name: ${board_name}_Status
    
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: True

light:
  - platform: neopixelbus
    variant: WS2812
    pin: GPIO25
    num_leds: 174
    type: GRB
    name: ${board_name}_LED
    method:
      type: esp32_rmt
      channel: 2
    id: light1
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:

  - platform: partition
    name: ${board_name}_toilet
    id: light1_toilet
    segments:
      - id: light1
        from: 157
        to: 173
    effects:
      - addressable_color_wipe:
      - automation:
          name: "Occupied"
          sequence:
            - light.turn_on:
                id: light1_toilet
                brightness: 50%
                transition_length: 3s
                red: 0%
                green: 100%
                blue: 0%
            - delay: 2s
            - light.turn_on:
                id: light1_toilet
                brightness: 20%
                transition_length: 2s
                red: 0%
                green: 100%
                blue: 0%
            - delay: 2s
      - automation:
          name: "Red_Alarm"
          sequence:
            - light.addressable_set:
                id: light1_toilet
                color_brightness: 100%
                red: 100%
                green: 0%
                blue: 0%
            - delay: 1s
            - light.addressable_set:
                id: light1_toilet
                color_brightness: 10%
                red: 100%
                green: 0%
                blue: 0%
            - delay: 1s
      - automation:
          name: "Green_Alarm"
          sequence:
            - light.addressable_set:
                id: light1_toilet
                color_brightness: 100%
                red: 0%
                green: 100%
                blue: 0%
            - delay: 1s
            - light.addressable_set:
                id: light1_toilet
                color_brightness: 20%
                red: 0%
                green: 100%
                blue: 0%
            - delay: 1s
            
  - platform: partition
    name: ${board_name}_bathroom
    id: light1_bathroom
    segments:
      - id: light1
        from: 99
        to: 117
    effects:
      - addressable_color_wipe:
      - automation:
          name: "Occupied"
          sequence:
            - light.turn_on:
                id: light1_bathroom
                brightness: 50%
                transition_length: 3s
                red: 0%
                green: 0%
                blue: 100%
            - delay: 2s
            - light.turn_on:
                id: light1_bathroom
                brightness: 20%
                transition_length: 2s
                red: 0%
                green: 0%
                blue: 100%
            - delay: 2s
      - automation:
          name: "Red_Alarm"
          sequence:
            - light.addressable_set:
                id: light1_bathroom
                color_brightness: 100%
                red: 100%
                green: 0%
                blue: 0%
            - delay: 1s
            - light.addressable_set:
                id: light1_bathroom
                color_brightness: 10%
                red: 100%
                green: 0%
                blue: 0%
            - delay: 1s
      - automation:
          name: "Green_Alarm"
          sequence:
            - light.addressable_set:
                id: light1_bathroom
                color_brightness: 100%
                red: 0%
                green: 100%
                blue: 0%
            - delay: 1s
            - light.addressable_set:
                id: light1_bathroom
                color_brightness: 5%
                red: 0%
                green: 100%
                blue: 0%
            - delay: 1s

  - platform: partition
    name: ${board_name}_washer
    id: light1_washer
    segments:
      - id: light1
        from: 90
        to: 98
    effects:
      - addressable_color_wipe:
      - automation:
          name: "Occupied"
          sequence:
            - light.turn_on:
                id: light1_washer
                brightness: 50%
                transition_length: 3s
                red: 0%
                green: 0%
                blue: 100%
            - delay: 2s
            - light.turn_on:
                id: light1_washer
                brightness: 20%
                transition_length: 2s
                red: 0%
                green: 0%
                blue: 100%
            - delay: 2s
      - automation:
          name: "Red_Alarm"
          sequence:
            - light.addressable_set:
                id: light1_washer
                color_brightness: 100%
                red: 100%
                green: 0%
                blue: 0%
            - light.addressable_set:
                id: light1_washer
                color_brightness: 10%
                red: 100%
                green: 0%
                blue: 0%
      - automation:
          name: "Washing"
          sequence:
            - light.turn_on:
                id: light1_washer
                color_brightness: 100%
                red: 100%
                green: 100%
                blue: 0%
                transition_length: 3s
            - delay: 1s
            - light.turn_on:
                id: light1_washer
                color_brightness: 10%
                red: 100%
                green: 100%
                blue: 00%
                transition_length: 5s
            - delay: 2s
      - automation:
          name: "Drying"
          sequence:
            - light.turn_on:
                id: light1_washer
                color_brightness: 100%
                red: 0%
                green: 0%
                blue: 100%
                transition_length: 3s
            - delay: 1s
            - light.turn_on:
                id: light1_washer
                color_brightness: 10%
                red: 10%
                green: 10%
                blue: 100%
                transition_length: 5s
            - delay: 2s
      - automation:
          name: "Error"
          sequence:
            - light.turn_on:
                id: light1_washer
                color_brightness: 100%
                red: 0%
                green: 100%
                blue: 0%
                transition_length: 2s
            - delay: 1s
            - light.turn_on:
                id: light1_washer
                color_brightness: 10%
                red: 100%
                green: 100%
                blue: 0%
                transition_length: 3s
            - delay: 1s
      - automation:
          name: "Green_Alarm"
          sequence:
            - light.addressable_set:
                id: light1_washer
                color_brightness: 100%
                red: 0%
                green: 100%
                blue: 0%
            - delay: 1s
            - light.addressable_set:
                id: light1_washer
                color_brightness: 5%
                red: 0%
                green: 100%
                blue: 0%
            - delay: 1s

text_sensor:
  - platform: template
    name: ${board_name}_Uptime
    lambda: |-
        int seconds = round(id(uptime_sensor).raw_state);
        int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600);
        int hours = seconds / 3600;
        seconds = seconds % 3600;
        int minutes = seconds /  60;
        seconds = seconds % 60;
        return (
          (days ? to_string(days) + "d " : "00d ") +
          (hours ? to_string(hours) + "h " : "00h ") +
          (minutes ? to_string(minutes) + "m " : "00m ") +
          (to_string(seconds) + "s")
        );
    icon: mdi:clock-start
    update_interval: 15s

  - platform: wifi_info
    ip_address:
      name: ${board_name}_IP
    ssid:
      name: ${board_name}_SSID
    bssid:
      name: ${board_name}_BSSID
    mac_address:
      name: ${board_name}_Mac
    scan_results:
      name: ${board_name}_Latest_Scan_Results

  - platform: version
    name: ${board_name}_ESPHome_Version
    hide_timestamp: true
    
sensor:
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor
    update_interval: 15s

  - platform: bme280
    temperature:
      name: ${board_name}_Temperature
      oversampling: 16x
      id: bme280_temperature
    pressure:
      name: ${board_name}_Pressure
      id: bme280_pressure
    humidity:
      name: ${board_name}_Humidity
      id: bme280_humidity
    address: 0x76
    update_interval: 30s

  - platform: bh1750
    name: ${board_name}_Illuminance
    address: 0x23
    #measurement_duration: 254
    update_interval: 15s
    accuracy_decimals: 0
    
  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s

button:
  - platform: restart
    name: ${board_name}_Restart

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Moscow