esphome:
  name: esp32_test
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid_k
  password: !secret wifi_pass
  domain: .localdomain
  reboot_timeout: 15min
  output_power: 17.5dB
  fast_connect: true
  power_save_mode: none

logger:

# Enable Home Assistant API
api:

ota:
