substitutions:
  board_name: esp8266_test

esphome:
  name: ${board_name}
  platform: ESP8266
  board: nodemcuv2
  comment: ESP8266 test

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  domain: .localdomain
  reboot_timeout: 15min
  output_power: 10dB
  fast_connect: true
  power_save_mode: none
  # manual_ip:
  #   static_ip: 192.168.1.248
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0
  #   dns1: 192.168.1.1
  #   dns2: 8.8.8.8
  # networks:
  #   - ssid: !secret wifi_ssid_hb
  #     password: !secret wifi_pass
  #     hidden: true
  #     bssid: !secret wifi_bssid_hb_iot
  #     priority: 2
  #   - ssid: !secret wifi_ssid
  #     password: !secret wifi_pass
  #     hidden: false
  #     bssid: !secret wifi_bssid_hb_main
  #     priority: 1
  #   - ssid: !secret wifi_ssid
  #     password: !secret wifi_pass
  #     hidden: false
  #     priority: 0

logger:
  baud_rate: 0
  
api:
  reboot_timeout: 15min

ota:

web_server:
  port: 80

binary_sensor:
  - platform: status
    name: ${board_name}_Status

sensor:
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor
    update_interval: 15s

  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s

  - platform: adc
    pin: VCC
    name: ${board_name}_Vcc
    update_interval: 15s

switch:
  - platform: restart
    name: ${board_name}_Restart