substitutions:
  board_name: gosund_strip_p1
  node_name: gosund-strip-p1

esphome:
  name: ${node_name}
  comment: Gosund Strip P1

esp8266:
  board: esp01_1m
  restore_from_flash: true


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  #domain: .local
  reboot_timeout: 15min
  fast_connect: true
  #use_address: 192.168.1.180
  #output_power: 17.5dB
  #power_save_mode: none
  # manual_ip:
    # static_ip: 192.168.1.180
    # gateway: 192.168.1.1
    # subnet: 255.255.255.0
    # dns1: 192.168.1.1
    # dns2: 8.8.8.8

logger:
  baud_rate: 0
  esp8266_store_log_strings_in_flash: false
  logs:
    adc: INFO

api:
  reboot_timeout: 0s

ota:

status_led:
  pin:
    number: GPIO02
    inverted: True

uart:
  rx_pin: GPIO03
  #tx_pin: GPIO01
  baud_rate: 4800

binary_sensor:
  - platform: status
    name: ${board_name}_Status

  - platform: gpio
    id: id_button
    internal: true
    pin:
      number: GPIO16
      inverted: true
      mode: INPUT
    on_press:
      - switch.toggle: relay4

  - platform: template
    id: buttonrelay1
    internal: true
    on_press:
      - switch.toggle: relay1
    filters:
      - delayed_off: 100ms

  - platform: template
    id: buttonrelay2
    internal: true
    on_press:
      - switch.toggle: relay2
    filters:
      - delayed_off: 100ms

  - platform: template
    id: buttonrelay3
    internal: true
    on_press:
      - switch.toggle: relay3
    filters:
      - delayed_off: 100ms

switch:
  - platform: gpio
    pin: GPIO14
    id: relay1
    restore_mode: RESTORE_DEFAULT_ON
    name: ${board_name}_Relay1
    icon: mdi:power-socket-eu

  - platform: gpio
    pin: GPIO12
    id: relay2
    restore_mode: RESTORE_DEFAULT_ON
    name: ${board_name}_Relay2
    icon: mdi:power-socket-eu

  - platform: gpio
    pin: GPIO13
    id: relay3
    restore_mode: RESTORE_DEFAULT_ON
    name: ${board_name}_Relay3
    icon: mdi:power-socket-eu

  - platform: gpio
    pin: GPIO05
    id: relay4
    restore_mode: RESTORE_DEFAULT_ON
    name: ${board_name}_Relay_USB
    icon: mdi:power-socket-eu
    inverted: yes

text_sensor:
  - platform: template
    name: ${board_name}_Uptime
    lambda: |-
        int seconds = round(id(uptime_sensor).raw_state);
        int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600);
        int hours = seconds / 3600;
        seconds = seconds % 3600;
        int minutes = seconds /  60;
        seconds = seconds % 60;
        return (
          (days ? to_string(days) + "d " : "00d ") +
          (hours ? to_string(hours) + "h " : "00h ") +
          (minutes ? to_string(minutes) + "m " : "00m ") +
          (to_string(seconds) + "s")
        );
    icon: mdi:clock-start
    update_interval: 15s

  - platform: wifi_info
    ip_address:
      name: ${board_name}_IP
    ssid:
      name: ${board_name}_SSID
    bssid:
      name: ${board_name}_BSSID
    mac_address:
      name: ${board_name}_Mac
    scan_results:
      name: ${board_name}_Latest_Scan_Results

  - platform: version
    name: ${board_name}_ESPHome_Version
    hide_timestamp: true

sensor:
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor
    update_interval: 15s

  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s

  - platform: cse7766
    current:
      name: ${board_name}_A
      unit_of_measurement: 'A'
      accuracy_decimals: 3
      icon: mdi:flash-outline
      device_class: current
    voltage:
      name: ${board_name}_V
      unit_of_measurement: 'V'
      accuracy_decimals: 1
      icon: mdi:flash-outline
      filters:
        - lambda: return x * 2.34245;
      device_class: voltage
    power:
      name: ${board_name}_W
      unit_of_measurement: 'W'
      id: id_power
      icon: mdi:flash-outline
      filters:
        - lambda: return x * 2.34245;
      device_class: power
    update_interval: 5s
    
  - platform: adc
    pin: GPIO17
    id: gpio17
    internal: true
    update_interval: 0.1s
    filters:
      - lambda: |-
          if(x >= 0.60 && x < 0.90){
            id(buttonrelay1).publish_state(true);
          } else if(x >= 0.30 && x < 0.60){
            id(buttonrelay2).publish_state(true);
          }
          else if(x > 0.10 && x < 0.30){
            id(buttonrelay3).publish_state(true);
          } else {
            id(buttonrelay1).publish_state(false);
            id(buttonrelay2).publish_state(false);
            id(buttonrelay3).publish_state(false);
          }
          return{};

button:
  - platform: restart
    name: ${board_name}_Restart
    
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Moscow

