substitutions:
  board_name: lt11_1
  node_name: lt11-1

esphome:
  name: ${node_name}
  friendly_name: LED Strip RGB MB
  comment: LT11 Led Strip

esp8266:
  board: esp8285

wifi:
  ssid: !secret wifi_ssid_mb
  password: !secret wifi_pass
  domain: .local
  reboot_timeout: 15min
  #output_power: 17.5dB
  fast_connect: true
  #power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.136
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 8.8.8.8

logger:
  baud_rate: 0

api:
  reboot_timeout: 0s

ota:

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${board_name}_Button
    on_press:
      - light.toggle: led_light

  - platform: status
    name: ${board_name}_Status

output:
- platform: esp8266_pwm
  pin: GPIO14
  frequency: 1000 Hz
  id: pwm_b
- platform: esp8266_pwm
  pin: GPIO12
  frequency: 1000 Hz
  id: pwm_g
- platform: esp8266_pwm
  pin: GPIO4
  frequency: 1000 Hz
  id: pwm_r
- platform: esp8266_pwm
  pin: GPIO5
  frequency: 1000 Hz
  id: pwm_w

light:
- platform: rgbw
  name: ${board_name}_LED
  red: pwm_r
  green: pwm_g
  blue: pwm_b
  white: pwm_w
  id: led_light
  effects:
    - flicker:
    - flicker:
        name: Flicker Effect With Custom Values
        alpha: 95%
        intensity: 1.5%
    - strobe:
    - strobe:
        name: Strobe Effect With Custom Values
        colors:
          - state: True
            brightness: 100%
            red: 100%
            green: 90%
            blue: 0%
            duration: 500ms
          - state: False
            duration: 250ms
          - state: True
            brightness: 100%
            red: 0%
            green: 100%
            blue: 0%
            duration: 500ms
    - random:
    - random:
        name: Random Effect With Custom Values
        transition_length: 5s
        update_interval: 7s
    - random:
        name: "My Slow Random Effect"
        transition_length: 30s
        update_interval: 30s
    - random:
        name: "My Fast Random Effect"
        transition_length: 4s
        update_interval: 5s

button:
  - platform: restart
    name: ${board_name}_Restart

sensor:
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor

  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s

text_sensor:
  - platform: template
    name: ${board_name}_Uptime
    lambda: |-
        int seconds = round(id(uptime_sensor).raw_state);
        int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600);
        int hours = seconds / 3600;
        seconds = seconds % 3600;
        int minutes = seconds /  60;
        seconds = seconds % 60;
        return (
          (days ? to_string(days) + "d " : "00d ") +
          (hours ? to_string(hours) + "h " : "00h ") +
          (minutes ? to_string(minutes) + "m " : "00m ") +
          (to_string(seconds) + "s")
        );
    icon: mdi:clock-start
    update_interval: 15s

  - platform: wifi_info
    ip_address:
      name: ${board_name}_IP
    ssid:
      name: ${board_name}_SSID
    bssid:
      name: ${board_name}_BSSID
    mac_address:
      name: ${board_name}_Mac
    scan_results:
      name: ${board_name}_Latest_Scan_Results

  - platform: version
    name: ${board_name}_ESPHome_Version
    hide_timestamp: true

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Moscow

syslog:
    ip_address: "192.168.1.26"
    port: 514