substitutions:
  board_name: s26_socket_3
  ip_address: 192.168.1.121

esphome:
  name: ${board_name}
  platform: ESP8266
  board: esp01_1m
  on_boot:
    if:
      condition:
        wifi.connected:
      then:
        - light.turn_on: wifi_led

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  domain: .local
  reboot_timeout: 15min
  manual_ip:
    static_ip: ${ip_address}
    gateway: 192.168.1.1
    subnet: 255.255.255.0

logger:
#  baud_rate: 0

api:
  reboot_timeout: 0s

ota:

web_server:
  port: 80
  
output:
  - platform: esp8266_pwm
    id: manual_status_led
    pin: 
      number: GPIO13
      inverted: false

light:
  - platform: monochromatic
    name: ${board_name}_Status_LED
    internal: true
    output: manual_status_led
    id: wifi_led

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: ${board_name}_Button
    on_press:
      - switch.toggle: relay

  - platform: status
    name: ${board_name}_Status

switch:
  - platform: gpio
    name: ${board_name}_Relay
    pin: GPIO12
    id: relay
    
sensor:
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor

  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s

text_sensor:
  - platform: template
    name: ${board_name}_Uptime
    lambda: |-
        int seconds = round(id(uptime_sensor).raw_state);
        int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600);
        int hours = seconds / 3600;
        seconds = seconds % 3600;
        int minutes = seconds /  60;
        seconds = seconds % 60;
        return (
          (days ? to_string(days) + "d " : "00d ") +
          (hours ? to_string(hours) + "h " : "00h ") +
          (minutes ? to_string(minutes) + "m " : "00m ") +
          (to_string(seconds) + "s")
        );
    icon: mdi:clock-start
    update_interval: 15s

time:
  - platform: homeassistant
    id: homeassistant_time