substitutions:
  board_name: sonoff_5v1c
  node_name: sonoff-5v1c

esphome:
  name: ${node_name}
  comment: Sonoff 5v Tablet Charging Module
  on_boot:
    priority: -10
    then:
    # on affter boot
    - switch.turn_on: relay
    
esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid_iot
  password: !secret wifi_pass
  #domain: .local
  reboot_timeout: 15min
  #output_power: 17.5dB
  #fast_connect: true
  #power_save_mode: none
  # manual_ip:
  #   static_ip: 192.168.1.186
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0
  #   dns1: 192.168.1.1
  #   dns2: 8.8.8.8

api:
  reboot_timeout: 0s

logger:
  baud_rate: 0
  esp8266_store_log_strings_in_flash: false

ota:

http_request:
  id: http_request_data

# web_server:
#   port: 80

# status_led:
#   pin:
#     number: GPIO13
#     inverted: yes

output:
  - platform: gpio
    id: green_led
    pin: GPIO13
    inverted: True

light:
  - platform: binary
    name: ${board_name}_Green_LED
    output: green_led
    id: id_green_led
    internal: true

number:
  - platform: template
    name: ${board_name}_MaxLevel
    icon: mdi:arrow-collapse-up
    id: id_max_level
    restore_value: true
    update_interval: 30s
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true

  - platform: template
    name: ${board_name}_MinLevel
    icon: mdi:arrow-collapse-down
    id: id_min_level
    restore_value: true
    update_interval: 30s
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true

binary_sensor:
  - platform: status
    name: ${board_name}_Status

  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${board_name}_Button
    on_press:
      - switch.toggle: relay
      
  - platform: template
    name: ${board_name}_auto_mode
    id: id_auto_mode

  # - platform: homeassistant
  #   name: ${board_name}_tod
  #   id: id_tod
  #   entity_id: binary_sensor.tod_day
  #   internal: false
  #   publish_initial_state: true

  - platform: template
    name: ${board_name}_ToD
    id: id_tod
    icon: mdi:chart-timeline

  - platform: homeassistant
    name: ${board_name}_security
    entity_id: switch.system_security_mode
    id: id_security
    internal: false
    publish_initial_state: true
    
switch:
  - platform: gpio
    name: ${board_name}_Relay
    pin: GPIO12
    id: relay

  - platform: template
    name: ${board_name}_always_on
    optimistic: true
    id: id_always_on
    on_turn_on:
      - binary_sensor.template.publish:
          id: id_auto_mode
          state: OFF
    on_turn_off:
      - binary_sensor.template.publish:
          id: id_auto_mode
          state: OFF    

sensor:
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor

  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s

  - platform: homeassistant
    name: ${board_name}_people
    entity_id: sensor.people_home
    id: id_people_home
    internal: false

  - platform: template
    name: ${board_name}_Battery_Level
    id: id_battery
    device_class: battery
    unit_of_measurement: '%'
    on_value:
      - if:
          condition:
              - binary_sensor.is_on: id_auto_mode
          then:
            - if:
                condition:
                  and:
                    - lambda: "return id(id_battery).state <= id(id_min_level).state;"
                    - switch.is_off: relay
                then:
                  - switch.turn_on: relay
                else:
                  - if:
                      condition:
                        and:
                          - lambda: "return id(id_battery).state >= id(id_max_level).state ;"
                          - switch.is_on: relay
                      then:
                        - switch.turn_off: relay
          else:
            - if: 
                condition:
                  - switch.is_off: relay
                then:
                  - switch.turn_on: relay            

  # - platform: homeassistant
  #   name: ${board_name}_bat_level
  #   entity_id: sensor.optima_8_z801_4g_battery
  #   id: battery
  #   internal: false
  #   device_class: battery
  #   unit_of_measurement: '%'
  #   filters:
  #     - heartbeat: 10s
  #   on_value:
  #     - if:
  #         condition:
  #             - binary_sensor.is_on: id_auto_mode
  #         then:
  #           - if:
  #               condition:
  #                 and:
  #                   - lambda: "return id(battery).state < 50;"
  #                   - switch.is_off: relay
  #               then:
  #                 - switch.turn_on: relay
  #               else:
  #                 - if:
  #                     condition:
  #                       and:
  #                         - lambda: "return id(battery).state > 70 ;"
  #                         - switch.is_on: relay
  #                     then:
  #                       - switch.turn_off: relay
  #         else:
  #           - if: 
  #               condition:
  #                 - switch.is_off: relay
  #               then:
  #                 - switch.turn_on: relay            

text_sensor:
  - platform: template
    name: ${board_name}_Uptime
    lambda: |-
        int seconds = round(id(uptime_sensor).raw_state);
        int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600);
        int hours = seconds / 3600;
        seconds = seconds % 3600;
        int minutes = seconds /  60;
        seconds = seconds % 60;
        return (
          (days ? to_string(days) + "d " : "00d ") +
          (hours ? to_string(hours) + "h " : "00h ") +
          (minutes ? to_string(minutes) + "m " : "00m ") +
          (to_string(seconds) + "s")
        );
    icon: mdi:clock-start
    update_interval: 15s

  - platform: wifi_info
    ip_address:
      name: ${board_name}_IP
    ssid:
      name: ${board_name}_SSID
    bssid:
      name: ${board_name}_BSSID
    mac_address:
      name: ${board_name}_Mac
    scan_results:
      name: ${board_name}_Latest_Scan_Results

  - platform: version
    name: ${board_name}_ESPHome_Version
    hide_timestamp: true

button:
  - platform: restart
    name: ${board_name}_Restart
    
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Moscow

interval:
  - interval: 15s
    then:
      - if:
          condition:
            and:
              - not:
                  - binary_sensor.is_on: id_security
              - or:
                  - not:
                      - binary_sensor.is_on: id_tod
                  - switch.is_on: id_always_on
          then:
            - binary_sensor.template.publish:
                id: id_auto_mode
                state: OFF
          else:
            - binary_sensor.template.publish:
                id: id_auto_mode
                state: ON

  - interval: 1min
    then:
      - http_request.get:
          url: !secret kiosk_url
          headers:
            Content-Type: application/json
          verify_ssl: false
          on_response:
            then:
              - lambda: |-
                  json::parse_json(id(http_request_data).get_string(), [](JsonObject root) {
                      id(id_battery).publish_state(root["batteryLevel"]);
                  });
      - if:
          condition:
              - lambda: "return id(id_min_level).state <= 20;"
          then:
            - number.set:
                id: id_min_level
                value: 25
      - if:
          condition:
              - lambda: "return id(id_max_level).state <= 50;"
          then:
            - number.set:
                id: id_max_level
                value: 80


  - interval: 30s
    then:
      - if:
          condition:
            or:
              - lambda: |-
                  return id(sntp_time).now().hour >= 21;
              - lambda: |-
                  return (id(sntp_time).now().hour >= 0 && id(sntp_time).now().hour < 7) ;
          then:
            - binary_sensor.template.publish:
                id: id_tod
                state: OFF
          else:
            - binary_sensor.template.publish:
                id: id_tod
                state: ON