substitutions:
  board_name: sonoff_dualr3_1

esphome:
  name: ${board_name}
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  #domain: .local
  reboot_timeout: 15min
  #output_power: 17.5dB
  fast_connect: true
  #power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.63
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 8.8.8.8

api:

ota:
  reboot_timeout: 0s
  
# web_server:
#   port: 80

logger:
  baud_rate: 0

uart:
  tx_pin: GPIO25
  rx_pin: GPIO26
  baud_rate: 38400
  parity: EVEN
  stop_bits: 1

sensor:
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor
    update_interval: 15s

  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s

  - platform: cse7761
    update_interval: 5s
    voltage:
      name: ${board_name}_Voltage
      accuracy_decimals: 1
      device_class: voltage
      id: id_voltage
    current_1:
      name: ${board_name}_Current_1
      accuracy_decimals: 1
      device_class: current
      id: id_current_1
    current_2:
      name: ${board_name}_Current_2
      accuracy_decimals: 1
      device_class: current
      id: id_current_2
    active_power_1:
      name: ${board_name}_Power_1
      accuracy_decimals: 0
      id: id_power_1
      unit_of_measurement: W
      device_class: power
    active_power_2:
      name: ${board_name}_Power_2
      accuracy_decimals: 0
      id: id_power_2
      unit_of_measurement: W
      device_class: power

  - platform: integration
    name: ${board_name}_Energy_1
    sensor: id_power_1
    time_unit: h
    accuracy_decimals: 3
    unit_of_measurement: 'kWh'
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001
    id: id_energy_1
    restore: true

  - platform: integration
    name: ${board_name}_Energy_2
    sensor: id_power_2
    time_unit: h
    accuracy_decimals: 3
    unit_of_measurement: 'kWh'
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001
    id: id_energy_2
    restore: true

switch:
  - platform: gpio
    name: ${board_name}_Relay_1
    id: sw1
    pin: GPIO27
    restore_mode: RESTORE_DEFAULT_ON

  - platform: gpio
    name: ${board_name}_relay_2
    id: sw2
    pin: GPIO14
    restore_mode: RESTORE_DEFAULT_ON

output:
  - platform: gpio
    id: blue_led
    pin: GPIO13
    #inverted: True

light:
  - platform: binary
    name: ${board_name}_StatusLED
    internal: true
    output: blue_led
    id: main_led

binary_sensor:
  - platform: status
    name: ${board_name}_Status

  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${board_name}_Button

  - platform: gpio
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: True
    name: ${board_name}_Switch_1

  - platform: gpio
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
      inverted: True
    name: ${board_name}_Switch_2

      
text_sensor:
  - platform: template
    name: ${board_name}_Uptime
    lambda: |-
        int seconds = round(id(uptime_sensor).raw_state);
        int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600);
        int hours = seconds / 3600;
        seconds = seconds % 3600;
        int minutes = seconds /  60;
        seconds = seconds % 60;
        return (
          (days ? to_string(days) + "d " : "00d ") +
          (hours ? to_string(hours) + "h " : "00h ") +
          (minutes ? to_string(minutes) + "m " : "00m ") +
          (to_string(seconds) + "s")
        );
    icon: mdi:clock-start
    update_interval: 15s

button:
  - platform: restart
    name: ${board_name}_Restart

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Moscow      