{
  "external_converters": [],
  "devices": [
    "devices.yaml"
  ],
  "groups": [
    "groups.yaml"
  ],
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://192.168.1.14:1883",
    "user": "mqtt",
    "password": "mqtt",
    "client_id": "z2m",
    "reject_unauthorized": true,
    "include_device_information": true,
    "keepalive": 60,
    "version": 4,
    "force_disable_retain": false
  },
  "serial": {
    "adapter": "ezsp",
    "port": "socket://192.168.1.73:8888"
  },
  "advanced": {
    "log_level": "info",
    "pan_id": 6784,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blocklist": [],
    "availability_passlist": []
  },
  "device_options": {},
  "blocklist": [],
  "passlist": [],
  "queue": {},
  "frontend": {
    "port": 8099
  },
  "experimental": {}
}
