# ############################################################################
# DB size sensors
# ############################################################################
#  - platform: filesize
#    name: Db Size
#    file_paths:
#      - /config/home-assistant_v2.db
#  - platform: template
#    sensors:
#      db_size:
#        value_template: "{{ states.sensor.home_assistant_v2_db.state | round(0, 'common' ,0) }}"
#        unit_of_measurement: Mb
#        friendly_name: 'DB size'

- platform: filesize
  file_paths:
    - /config/home-assistant.log

- platform: sql
  db_url: !secret postgresql_url
  queries:
    - name: DB Size
      query: "SELECT (pg_database_size('hass')/1024/1024) as db_size;"
      column: "db_size"
      unit_of_measurement: Mb
  scan_interval: 60

# - platform: sql
#   db_url: !secret mariadb_url
#   queries:
#   - name: DB Size
#     query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 0) "value" FROM information_schema.tables WHERE table_schema="hass" GROUP BY table_schema;'
#     column: 'value'
#     unit_of_measurement: Mb
#   scan_interval: 30

# Influx DB Size
- platform: influxdb
  host: !secret influxdb_host
  port: !secret influxdb_port
  username: !secret influxdb_username
  password: !secret influxdb_password
  queries:
    - name: InfluxDB Size
      unit_of_measurement: MB
      value_template: "{{ (value | float(0) / 1024 /1024) | round(0, 'common' ,0) }}"
      group_function: mean
      measurement: '"monitor"."shard"'
      database: _internal
      where: 'time > now() - 1m AND "database"=''hass'''
      field: diskBytes

- platform: mqtt
  name: InfluxDB Hass Size
  state_topic: "ubuntu/db_stats/influxdb_hass_size"
  value_template: "{{ ( value | float(0) / 1024) |round(0, 'common' ,0) }}"
  unit_of_measurement: "Mb"
  expire_after: 150
  icon: mdi:database
  force_update: true

- platform: mqtt
  name: InfluxDB Hass Autogen Size
  state_topic: "ubuntu/db_stats/influxdb_hass_autogen_size"
  value_template: "{{ ( value | float(0) / 1024) |round(0, 'common' ,0) }}"
  unit_of_measurement: "Mb"
  expire_after: 150
  icon: mdi:database
  force_update: true

- platform: mqtt
  name: InfluxDB Hass Infinite Size
  state_topic: "ubuntu/db_stats/influxdb_hass_infinite_size"
  value_template: "{{ ( value | float(0) / 1024) |round(0, 'common' ,0) }}"
  unit_of_measurement: "Mb"
  expire_after: 150
  icon: mdi:database
  force_update: true

- platform: mqtt
  name: InfluxDB Internal Size
  state_topic: "ubuntu/db_stats/influxdb_internal_size"
  value_template: "{{ ( value | float(0) / 1024) |round(0, 'common' ,0) }}"
  unit_of_measurement: "Mb"
  expire_after: 150
  icon: mdi:database
  force_update: true

- platform: mqtt
  name: InfluxDB Total Size
  state_topic: "ubuntu/db_stats/influxdb_size"
  value_template: "{{ ( value | float(0) / 1024 ) |round(0, 'common' ,0) }}"
  unit_of_measurement: "Mb"
  expire_after: 150
  icon: mdi:database
  force_update: true

- platform: mqtt
  name: PostgreSQL Total Size
  state_topic: "ubuntu/db_stats/postgre_size"
  value_template: "{{ ( value | float(0) / 1024 / 1024 ) |round(0, 'common' ,0) }}"
  unit_of_measurement: "Mb"
  expire_after: 150
  icon: mdi:database
  force_update: true

# ############################################################################
# DB size sensors - Speed
# ############################################################################
- platform: statistics
  entity_id: sensor.db_size
  name: db_size_statistics
  sampling_size: 20000
  max_age:
    minutes: 60

- platform: statistics
  entity_id: sensor.influxdb_total_size
  name: influxdb_size_statistics
  sampling_size: 20000
  max_age:
    minutes: 60
