# ############################################################################
# Hardware sensors - Internal HA
# ############################################################################
- platform: cpuspeed

- platform: systemmonitor
  resources:
    - type: last_boot
    - type: memory_use_percent
    - type: processor_use
    - type: processor_temperature
    - type: swap_use
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: disk_use_percent
      arg: /
    - type: network_in
      arg: eno1
    - type: network_out
      arg: eno1
    - type: throughput_network_in
      arg: eno1
    - type: throughput_network_out
      arg: eno1
    - type: packets_in
      arg: eno1
    - type: packets_out
      arg: eno1
# - platform: command_line
#   name: CPU Temperature
#   command: "cat /sys/class/thermal/thermal_zone0/temp"
#   unit_of_measurement: "°C"
#   value_template: '{{ value | multiply(0.001) | round(0, 'common' ,0) }}'

#  - platform: command_line
#    name: GPU Temperature
#    command: "/opt/vc/bin/vcgencmd measure_temp"
#    unit_of_measurement: "°C"
#    value_template: '{{ value | replace("temp=", "") | replace("''C", "") | round(0, 'common' ,0) }}'
